## Script for creating and building the dynatop R package
rm(list=ls())
graphics.off()

## path of the package
pacPath <- '../'
Rcpp::compileAttributes(pacPath)
devtools::document(pacPath)
devtools::check(pacPath)

## check documentation build
pkgdown::clean_site(pacPath)
pkgdown::build_site(pacPath)
pkgdown::clean_site(pacPath)

## build, populate drat
## linux
dratPath <- "~/Documents/Software/drat"
buildFile <- devtools::build(pacPath)
install.packages(buildFile)
drat::insertPackage(buildFile,dratPath)

## mac and windows
rhub::validate_email() # for first time that session
pkgName <- sub('\\.tar.gz$', '', basename(buildFile)) 
## rhub::platforms()[,1] # lists platforms

mch <- rhub::check(path = buildFile,
                   platform = c("macos-highsierra-release-cran","windows-x86_64-release",
                                "macos-m1-bigsur-release"))
ext <- c(".tgz",".zip",".tgz")
outPath <- dirname(buildFile)
for(ii in 1:2){ ## m1 not fixed yet in drat
    tmp <- paste0(pkgName,ext[ii])
    outFile <- file.path(outPath,tmp)
    #download.file(file.path(mch$urls()$artifacts[ii],tmp),outFile)
    drat::insertPackage(outFile,dratPath)
}

## tidy up drat
drat::pruneRepo(dratPath,pkg="dynatop",remove="git")## this only does source files

## prior to submission
## submit to win-builder (release and devel) and macbuilder
## run locally with R CMD check --as-cran --use-valgrind ...
## run locally with r-devel and ASAN build

## tmp <- devtools::check_win_devel(pkg = buildFile)
## devtools::check_win(pkg = buildFile)
## devtools::check_mac(pkg = buildFile)


###########################################################################
## This converts the data for Swindale into the data object used in the examples.
rm(list=ls())
pacPath <- '../'
devtools::load_all(pacPath)
model <- readRDS("Swindale_exp.rds")
model$precip_input$name <- "Rainfall"
model$pet_input$name <- "PET"


qr <- read.csv( "start=2009-11-18_end=2009-11_4_int=0.25-hours_units=mm.hr-1.tsv",sep="\t")
obs <- as.xts(qr[,c("Flow","Rainfall")],order.by= as.POSIXct(qr[,'Date'],format="%d/%m/%Y %H:%M",tz='GMT'))
## According to original notes and code Flow in cumecs and precip in mm/timestep
obs$Rainfall <- obs$Rainfall/1000 # convert to m/timestep
obs$PET <- evap_est(index(obs),0,5/1000) # in m

Swindale <- list(model=model,obs=obs)
save("Swindale",file="../data/Swindale.rda")






## ########################################
## This code uses Swindale and calls all the different transmissivity profiles
## with models generated by dynatopGIS
rm(list=ls())
devtools::load_all("../")
data("Swindale");
for(ii in list.files(".",pattern="^Swindale.*\\.rds$")){
    print(ii)
    mdl <- readRDS(ii)
    mdl$precip_input$name <- "Rainfall"
    mdl$pet_input$name <- "PET"
    dt <- dynatop$new(mdl)$add_data(Swindale$obs)#[1:2,,drop=FALSE])
    dt$initialise()$sim_hillslope()
    print(range(dt$get_mass_errors()[,6]))
    print(warnings())    
}

## ##############################
## simple run for debugging
rm(list=ls())
devtools::load_all("../")
data("Swindale");
ii <- list.files(".",pattern="^Swindale.*\\.rds$")[4]
mdl <- readRDS(ii)
mdl$precip_input$name <- "Rainfall"
mdl$pet_input$name <- "PET"
dt <- dynatop$new(mdl)$add_data(Swindale$obs)#[1:2,,drop=FALSE])
dt$initialise()$sim_hillslope()
dt$plot_channel_inflow()
dt$plot_channel_inflow(total=TRUE,separate=FALSE)
dt$plot_channel_inflow(total=TRUE,separate=TRUE)
dt$plot_channel_inflow(total=FALSE,separate=FALSE)
dt$plot_channel_inflow(total=FALSE,separate=TRUE)
plot(dt$get_channel_inflow(total=T))


graphics.off()
x <- xts(cbind(1:10,10:1),order.by=as.POSIXct("2020-01-01") + seq(0,600,length=10))
pf <- function(x){
    #oldpar <- par(no.readonly = TRUE)
    #on.exit(par(oldpar))
    par(mfrow=c(2,1))
    print(plot(x[,1]))
    print(plot(x[,2],on=NA))
}
pf(x)
