---
title: "Banding of HSUs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Banding of HSUs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
--- 

# Banding logic

This document tries to explain the logic in the process of combining
computational bands. Suppose these is a model with 6 classes of HSU
(a-f), whose original computational bands are numbered 1 to n, with 1
being the head of the catchment. These bands are to be combined into new
bands identified by Roman numerals.

## Head of the catchment

At the head of the catchment the first band (band 1) does not receive
any inflow to the saturated zone. Band 2 can receive inflows from Band
1, Band 3 can receive inflows from Bands 1 & 2, Band 4 can receive
inflows from Bands 1, 2 and 3 and so on.

The following diagram outlines the current situation where the shaded
boxes represent the combinations of bands and classes which occur.

  ---------- ------ --- --- --- --- --- ---
  New band   band   a   b   c   d   e   f
  I          1      X   X   X           
             2      X   X           X   X
             3      X   X   X   X   X   
             4      X       X   X   X   X
             5      X           X       
  ---------- ------ --- --- --- --- --- ---

This is simplified this into new bands based on assigning one new HSU
per class. This area of the new HSU is the sum of the areas of the old
HSUs in the same class. Similarly the length of the new HSU is the sum
of the lengths of the old HSUs of the same class.

The redistribution of flows from the HSU is by necessity a
simplification of the original structure. One approach would be to
assign flows based on the flow division of the most downslope (highest
band) of the original HSUs. This however may result in 'orphan' HSUs
which receive no subsurface inflow unless present in earlier bands.

The approach proposed is to evaluate the new HSUs in order of the first
occurrence of the class in the original bands which gives:

  ---------- ------ --- --- --- --- --- ---
  New band   band   a   b   c   d   e   f
  I                 X   X   X           
  Ii                                X   X
  iii                           X       
                                        
                                        
  ---------- ------ --- --- --- --- --- ---

This is itself not adequate to ensure that no HSUs are 'orphaned'. To
achieve this we also need to re-evaluate the distribution of fluxes from
each HSU to represent fluxes between classes for all of the original
bands. We do this as for the original classification but ignoring the
fluxes between HSUs on the same new band.

```{r}
bmdl <- band_model(model,50)
check_model(bmdl)
bmdl$Fsz[bmdl$Fsz>1] <- 1
bmdl$Fsf[bmdl$Fsf>1] <- 1
check_model(bmdl)
bmdl$hillslope[,'pet'] <- "PET"
bmdl$hillslope[,'precip'] <- "Rainfall"
profvis::profvis({btmp <- dynatop(bmdl,obs,0.015)})
```
