---
title: "The Hillslope HRU"
output: 
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
    number_sections: false
    toc: true
    toc_depth: 2
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{The Hillslope HRU}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Conceptual model

One of the underlying principles of dynamic TOPMODEL is that the landscape can
be broken up into hydrologically similar regions, or Hydrological Response
Units (HRUs), where all the area within a HRU behaves in a hydrologically
similar fashion. Further discussion and the connection of HRUs is outlined [elsewhere](Notes_on_the_implementation_of_Dynamic_TOPMODEL.html).

This document outlines the conceptual structure and computational
implementation of the hillslope HRU. The hillslope HRU is a representation of 
an area of hill slope with, for example, similar topographic, soil and upslope area
characteristics.

The hillslope HRU is considered to be a area of hill slope with outflow
occurring across a specified width of it boundary.
It is formed of four zones representing the surface water, which
passes water between HRUs and drains to the root zone. The root zone characterises
the interactions between evapotranspiration and precipitation and when full spills to
the unsaturated zone. This drains to the saturated zone which also interacts
with other HRUs. The behaviour of the saturated zone is modelled using a kinematic wave
approximation.

In the following section the governing equations of the hillslope HRU are
given in a finite volume form. For comparison we also outline the equivalent
equations for an infinitesimal vertical slab across the outflow width which is in keeping with the
original derivation of Dynamic TOPMODEL. An implicit numerical scheme, valid
for a wide range of transmissivity profiles, is then presented. The vignette
then concludes by presenting the tranmissivity profiles present within the code.

# Notation

Table \@ref(tab:hs-x-notation) outlines the notation used for describing an
infinitesimal slab across the hillslope HRU. 

The following conventions are used:

-   All properties such as slope angles and time constants are considered
    uniform along the hillslope.
	
-   Precipitation and Potential Evapotranspiration occur at spatially uniform
    rates.
	
-   All fluxes $r_{\star \rightarrow \star}$ are considered to be positive when
	travelling in the direction of the arrow, but can, in some cases be negative.

-   All fluxes $l_{\star}$ and $q_{\star}$ are considered to be positive flows travelling downslope.

-   The superscripts $^+$ and $^-$ are used to denote variables for the outflow
    and inflow to the hillslope.

-   $\left.y\right\rvert_t$ indicates the value of the
    variable $y$ at time $t$

-   Spatial averages are denoted with a $\bar{}$ so for example integrating
over the length of the hillslope $\Delta x$ we find

\begin{equation}
\int\limits_{0}^{\Delta x} wy dx = A\bar{y}
\end{equation}

-   Average values over a time step are denoted with a $\hat{}$. If the
    temporal average is of a spatial average the $\bar{}$ is dropped. For
    example the temporal average of the spatial average $bar{y}$ over a time step is $\hat{y}$.
	
| Quantity type              | Symbol                  | Description                                                        | unit    |
| ---                        | ---                     | ------                                                             | ---     |
| Storage                    | $s_{sf}$                | Surface excess storage per unit width                              | m       |
|                            | $s_{rz}$                | Root zone storage per unit width                                   | m       |
|                            | $s_{uz}$                | Unsaturated zone storage per unit width                            | m       |
|                            | $s_{sz}$                | Saturated zone storage deficit per unit width                      | m       |
| Vertical fluxes            | $r_{sf \rightarrow rz}$ | Flow from the surface excess store to the root zone per unit width | m/s     |
|                            | $r_{rz \rightarrow uz}$ | Flow from the root zone to the unsaturated zone per unit width     | m/s     |
|                            | $r_{uz \rightarrow sz}$ | Flow from unsaturated to saturated zone per unit width             | m/s     |
| Lateral fluxes             | $l_{sf}$                | Lateral flow in the surface zone per unit width                    | m$^2$/s |
|                            | $l_{sz}$                | Lateral flow in the saturated zone per unit width                  | m$^2$/s |
|                            | $q_{sf}$                | Lateral flow in the hillslope surface zone                         | m$^3$/s |
|                            | $q_{sz}$                | Lateral inflow to the hillslope surface zone                       | m$^3$/s |
| Vertical fluxes to the HRU | $p$                     | Precipitation rate                                                 | m/s     |
|                            | $e_p$                   | Potential Evapotranspiration rate                                  | m/s     |
| Other HRU properties       | $A$                     | Plan area                                                          | m$^3$   |
|                            | $w$                     | Width of outlet cross section                                      | m       |
|                            | $\Delta x$              | Length of the hillslope HRU                                        | m       |
|                            | $k_{sf}$                | Maximum flow rate from surface excess to root zone per unit width  | m/s     |
|                            | $c_{sf}$                | Surface excess storage celerity                                    | m/s     |
|                            | $s_{rzmax}$             | Maximum root zone storage depth                                    | m       |
|                            | $T_d$                   | Unsaturated zone time constant per m of saturated storage deficit. | s/m     |
|                            | $\Theta_{sz}$           | Further properties and parameters for the solution of the saturated zone | :-: |
                                                    
  Table: (\#tab:hs-x-notation) Outline of notation for describing a cross
  section of the hillslope HRU

# Finite Volume Formulation

In this section a finite volume formulation of the Dynamic TOPMODEL equations
is derived. 

## Surface zone

The storage in the surface zone satisfies $s_{sf} \geq 0$.
Surface storage is increased by lateral downslope flow from upslope HRUs. 
Water flows to the root zone at a constant rate $k_{sf}$, unless limited by
the available storage at the surface or the ability of the root zone to
receive water (for example if the saturation storage deficit is 0 and the root zone storage is full).

In cases where lateral flows in the saturated zone produce
saturation storage deficits water may be returned from the root
zone to the surface giving negative values of $r_{sf \rightarrow rz}$.

The governing ODE can be written as
\begin{equation}
\frac{dws_{sf}}{dt} = - \frac{dq_{sf}}{dx} - wr_{sf \rightarrow rz}
\end{equation}
where $r_{sf \rightarrow rz} \leq k_{sf}$.

Integration over the length $\Delta x$ and substituting in the spatial averages gives
\begin{equation}
A\frac{d \bar{s}_{sf}}{dt} = q_{sf}^{-} - q_{sf}^{+} - A\bar{r}_{sf \rightarrow rz}
\end{equation}

Dividing through by $w^+$ and re arranging gives
\begin{equation}
\frac{d \bar{s}_{sf}}{dt} = \frac{q_{sf}^{-}/w^{+} - l_{sf}^{+}}{A/w^+} - \bar{r}_{sf \rightarrow rz}
\end{equation}
This equation represents the evolution in time of $\bar{s}_{sf}$ expressed in
terms of the unit width fluxes and an effective length $A/w^+$

To complete the formulation assume that $l_{sf}^{+} = c_{sf}\bar{s}_{sf}$
which gives
\begin{equation}
\frac{d \bar{s}_{sf}}{dt} = \frac{q_{sf}^{-}}{A} - \bar{r}_{sf \rightarrow rz}
- \frac{w^{+}c_{sf}}{A} \bar{s}_{sf}
\end{equation}

### Infinitesimal slab

A similar expression for the evolution can be derived by considering the
infinitesimal slab at the downslope end of the HRU. Taking a discrete
approximation for the change of flow with length the governing ODE can be written as
\begin{equation}
\frac{dw^{+}s_{sf}^{+}}{dt} = \frac{q_{sf}^{-} - q_{sf}^{+}}{\Delta x} - w^{+}r_{sf \rightarrow rz}^{+}
\end{equation}

Dividing through by $w^{+}$ gives
\begin{equation}
\frac{ds_{sf}^{+}}{dt} = \frac{q_{sf}^{-}/w^{+} - l_{sf}^{+}}{\Delta x} - r_{sf \rightarrow rz}^{+}
\end{equation}

Note the similaties between this and the finite volume solution. Infact if
$r_{sf \rightarrow rz}$ is taken to be spatially uniform and 
$\Delta x = A/w^{+}$ then this solution for $s_{sf}^{+}$ will evolve in a similar fashion to
$\bar{s}_{sf}$

## Root zone

The root zone gains water from precipitation and the surface zone. It loses water through
evaporation and to the unsaturated zone. Since
all the veritcal fluxes are spatially uniform the evolution can be evaluated
in terms of the spatial averages. The root zone storage satifies

\begin{equation} 0 \leq \bar{s}_{rz} \leq s_{rzmax} \end{equation}

with the governing ODE
\begin{equation}
\frac{d\bar{s}_{rz}}{dt} = p - \frac{e_p}{s_{rzmax}} \bar{s}_{rz} +
\bar{r}_{sf\rightarrow rz} - \bar{r}_{rz \rightarrow uz}
\end{equation}

Fluxes from the surface and to the unsaturated zone are
controlled by the level of root zone storage along with the state of the unsaturated
and saturated zones.

For $\bar{s}_{rz} \leq s_{rzmax}$ then $\bar{r}_{rz \rightarrow uz} \leq 0$. Negative
values of $\bar{r}_{rz \rightarrow uz}$ may occur only when water is returned from the
unsaturated zone due to saturation caused by lateral inflow to the saturated zone.

When $\bar{s}_{rz} = s_{rzmax}$ then 
\begin{equation}
p - e_p + \bar{r}_{sf\rightarrow rz} - \bar{r}_{rz \rightarrow uz} \leq 0
\end{equation}
In this case $\bar{r}_{rz \rightarrow uz}$ may be positive if
\begin{equation}
p - e_p + \bar{r}_{sf\rightarrow rz} > 0
\end{equation}
so long as the unsaturated zone can receive the water. If $\bar{r}_{rz
\rightarrow uz}$ is 'throttled' by the rate at which the unsaturated zone can
receive water, then $\bar{r}_{sf\rightarrow rz}$ is adjusted (potentially becoming
negative) to ensure the equality is met.

### Infinitesimal slab

The same formulation follows for the infinitesimal slab at the bottom of the
hillslope with the averaged terms (using $\bar{}$) replaced with those valid
at the bottom of the hillslope (using $^{+}$).

## Unsaturated Zone

The unsaturated zone acts as a non-linear tank subject to the constraint 
\begin{equation} 0 \leq \bar{s}_{uz} \leq \bar{s}_{sz} \end{equation}

The governing ODE is written as
\begin{equation}
\frac{d\bar{s}_{uz}}{dt} = \bar{r}_{rz \rightarrow uz} - \bar{r}_{uz \rightarrow sz}
\end{equation}

If water is able to pass freely to the saturated zone, then it flows at the rate
$\frac{\bar{s}_{uz}}{T_d \bar{s}_{sz}}$. If $\bar{s}_{sz}=\bar{s}_{uz}=0$ this is interpreted to mean
that the flow rate is $\frac{1}{T_d}$. 
In this situation where $\bar{s}_{sz}=\bar{s}_{uz}$ the subsurface below
the root zone can be considered saturated, as in there is no further available
storage for water, but separated into parts: an upper part with vertical
flow and a lower part with lateral flux.

It is possible that $\bar{r}_{uz \rightarrow sz}$ is
constrained by the ability of the saturated zone to receive water. If
this is the case $\bar{r}_{uz \rightarrow sz}$ occurs at the maximum
possible rate and $\bar{r}_{rz \rightarrow uz}$ is limited to ensure that
$\bar{s}_{uz} \leq \bar{s}_{sz}$.

### Infinitesimal slab

The same formulation follows for the infinitesimal slab at the bottom of the
hillslope with the averaged terms (using $\bar{}$) replaced with those valid
at the bottom of the hillsipe (using $^{+}$).

## Saturated Zone

For a HRU the alteration of the storage in the saturated zone is
given by
\begin{equation}
\frac{dw\left(D-s_{sz}\right)}{dt} = -\frac{dq_{sz}}{dx} + wr_{uz \rightarrow sz}
\end{equation}

Integration over the length of the hillslope and substitution of the
spatial averaged values gives
\begin{equation}
-A\frac{d\bar{s}_{sz}}{dt} = q_{sz}^{-} - q_{sz}^{+}  + A\bar{r}_{uz \rightarrow sz}
\end{equation}

Dividing through by $w^+$ and rearranging gives
\begin{equation}
\frac{d\bar{s}_{sz}}{dt} = \frac{l_{sz}^{+} - q_{sz}^{-}/w^{+}}{A/w^{+}} - \bar{r}_{uz \rightarrow sz}
\end{equation}

The Kinematic approximation then depends upon the specification of a relationship
 between $\bar{s}_{sz}$ and $l_{sz}^{+}$. This usually termed the transmissivity
 profile however the use of the average, rather than cross sectional saturated
 storage deficit means this term is used only loosely. More generally the
 relationship is taken
to be a one-to-one, continuously differentiable function 
$g: \mathcal{R^{+}}\rightarrow \mathcal{R}^{+}$ which returns the lateral flow on
a unit width such that $l_{sz}^{+} = g\left(\bar{s}_{sz},\Theta_{sz}\right)
 \geq 0$ which satisfies
\begin{equation}
-\frac{dl_{sz}^{+}}{d\bar{s}_{sz}} = -\frac{d}{d\bar{s}_{sz}}g\left(\bar{s}_{sz},\Theta_{sz}\right) > 0
\end{equation}

The later condition ensures a positive celerity (wave speed) and indicates that $l_{sz}^{+}$ increases with decreasing
$\bar{s}_{sz}$. This is numerically helpful but not strictly required.

Using the relationship between $l_{sz}^{+}$ and $\bar{s}_{sz}$ gives
\begin{equation}
\frac{d\bar{s}_{sz}}{dt} = \frac{w^{+}}{A}g\left(\bar{s}_{sz},\Theta_{sz}\right) - \frac{q_{sz}^{-}}{A} - \bar{r}_{uz \rightarrow sz}
\end{equation}

### Infinitesimal slab

Evaluating for the foot of the hillslope and taking a discrete approximation
of the spatial gradient gives
\begin{equation}
\frac{ds_{sz}^{+}}{dt} = \frac{l_{sz}^{+} - q_{sz}^{-}/w^{+}}{\Delta x} - r_{uz \rightarrow sz}^{+}
\end{equation}

As with the surface zone we see the similarity in form, indicating that,
subject to the evaluation of the temporal integral, the two formulations
should return the same results when $\Delta x = A/w^{+}$


# Temporal Integration

No analytical solution yet exists for simultaneous integration of the system of
ODEs outlined above. In the following an implicit scheme, where fluxes
between stores are considered constant over the time step and gradients are
evaluated at the final state, is presented.

The basis of the solution is that a gravity driven system will maximise
the downward flow of water within each timestep of size $\Delta t$. 

## Approximating Equations

Recalling that the temporal and spatial average vertical fluxes are denoted with
a $\hat{}$ the implicit approximations are stated in teh following sections using the unknown vertical fluxes
$\hat{r}_{\star \rightarrow \star}$ which are then determined by maximising the
downward flux.

### Surface excess

The implicit scheme gives

\begin{equation}
\left. \bar{s}_{sf}  \right\rvert_{\Delta t}
=
\left. \bar{s}_{sf} \right\rvert_{0}
+ \Delta t \left(
\frac{\hat{q}_{sf}^{-}}{A} - 
\hat{r}_{sf \rightarrow rz}
- \frac{w^{+}c_{sf}}{A} \left. \bar{s}_{sf}  \right\rvert_{\Delta t}
\right)
\end{equation}
or 
\begin{equation}
\left. \bar{s}_{sf}  \right\rvert_{\Delta t}
= \left(1 + \frac{w^{+}c_{sf}}{A}\right)^{-1}
\left( \left. \bar{s}_{sf} \right\rvert_{0}
+ \Delta t \left(
\frac{\hat{q}_{sf}^{-}}{A} - 
\hat{r}_{sf \rightarrow rz}
\right) \right)
\end{equation}

To ensure that the surface storage does not become negative
\begin{equation}
\hat{r}_{sf \rightarrow rz} \leq \min\left( k_{sf},
\left. \bar{s}_{sf} \right\rvert_{0} + \frac{\Delta t \hat{q}_{sf}^{-}}{A}
\right)
\end{equation}

The surface outflow over the time step is evaluated as
\begin{equation}
\hat{q}_{sf}^{+} = \frac{w^{+}c_{sf}}{A} \left. \bar{s}_{sf}  \right\rvert_{\Delta t}
\end{equation}

### Root Zone

The implicit formulation for the root zone gives
\begin{equation}
\left. \bar{s}_{rz} \right.\rvert_{\Delta t} = 
\left( 1 + \frac{e_{p}\Delta t}{s_{rzmax}} \right)^{-1}
\left(
\left. \bar{s}_{rz} \right.\rvert_{0}
+ \Delta t \left(
p + \hat{r}_{sf \rightarrow rz} - \hat{r}_{rz \rightarrow uz} \right)
\right)
\end{equation}

Since flow to the unsaturated zone occur only to keep 
$\bar{s}_{rz} \leq s_{rzmax}$ then
\begin{equation}
\hat{r}_{rz \rightarrow uz} \leq \max\left(0,
\frac{1}{\Delta t}\left(
\left. \bar{s}_{rz} \right.\rvert_{0}
+ \Delta t \left(
p + \hat{r}_{sf \rightarrow rz} - e_{p} \right)
- s_{rzmax}
\right)\right)
\end{equation}

### Unsaturated Zone

The expression for the unsaturated zone is given in terms of
$\left. \bar{s}_{uz} \right.\rvert_{\Delta t}$ and 
$\left. \bar{s}_{sz} \right.\rvert_{\Delta t}$ as

\begin{equation}
\left. \bar{s}_{uz} \right.\rvert_{\Delta t} = 
\frac{T_{d}\left. \bar{s}_{sz} \right.\rvert_{\Delta t}}{
T_{d}\left. \bar{s}_{sz} \right.\rvert_{\Delta t} + \Delta t}
\left( \left. \bar{s}_{uz} \right.\rvert_{0} + \Delta t \hat{r}_{rz
\rightarrow uz}\right)
\end{equation}

Since $\left. \bar{s}_{uz} \right.\rvert_{\Delta t} \leq \left. \bar{s}_{sz}
	   \right.\rvert_{\Delta t}$ this places an additional condition of
\begin{equation}
\hat{r}_{rz \rightarrow uz} \leq \frac{1}{\Delta t} \left(
\left. \bar{s}_{sz} \right.\rvert_{\Delta t} + \frac{\Delta t}{T_d} - \left. \bar{s}_{uz} \right.\rvert_{0}\right)
\end{equation}

This condition also implies that $\hat{r}_{uz \rightarrow sz} \leq
								  \frac{1}{T_d}$

### Saturated Zone

Initial evaluation and substitution of the flux from the unsaturated zone gives
\begin{equation}
\left. \bar{s}_{sz}\right.\rvert_{\Delta t} = 
\left. \bar{s}_{sz}\right.\rvert_{\Delta 0} + \Delta t \left(
\frac{w^{+}}{A}g\left(\left.\bar{s}_{sz}\right\rvert_{\Delta t}\right) -
\frac{q_{sz}^{-}}{A} - \frac{
\left. \bar{s}_{uz} \right.\rvert_{0} + \Delta t \hat{r}_{rz \rightarrow uz} }
{ T_{d}\left. \bar{s}_{sz} \right.\rvert_{\Delta t} + \Delta t}
\right)
\end{equation}

Limiting the inflow by reaching the saturation level gives

\begin{equation}
\hat{r}_{rz \rightarrow uz} \leq \frac{1}{\Delta t}\left(
\left. \bar{s}_{sz}\right.\rvert_{\Delta 0} + \Delta t \left(
\frac{w^{+}}{A}g\left(0,\Theta_{sz}\right) -
\frac{q_{sz}^{-}}{A}\right) - \left. \bar{s}_{uz} \right.\rvert_{0} \right)
\end{equation}

Selecting $\bar{s}_{sz}$ to satisfy the above equation describes a non-linear
problem. However, since the LHS is strictly increasing with $\bar{s}_{sz}$,
while the RHS is decreasing so single solution is present and can be reliably
located.

## Algorithm

An implementation of the approximating equations which is consistent with
maximising the downward flux which makes use of the psuedo-function 
$f\left(\check{s}_{sz},\check{r}_{rz \rightarrow uz}\right)$ which returns the
value
\begin{equation}
\check{s}_{sz} - 
\left. \bar{s}_{sz}\right.\rvert_{\Delta 0} - \Delta t \left(
\frac{w^{+}}{A}g\left(\check{s}_{sz},\Theta_{sz}\right) -
\frac{q_{sz}^{-}}{A} - \min\left(\frac{1}{T_d},
\frac{ \left. \bar{s}_{uz} \right.\rvert_{0} + \Delta t \check{r}_{rz \rightarrow uz} }
{ T_{d} \check{s}_{sz} + \Delta t} \right)
\right)
\end{equation}

takes the following steps:

1. Compute $\check{r}_{sf \rightarrow rz} = \min\left( k_{sf},
\left. \bar{s}_{sf} \right\rvert_{0} + \frac{\Delta t \hat{q}_{sf}^{-}}{A}
\right)$
2. Compute $\check{r}_{rz \rightarrow uz} = \max\left(0, \frac{1}{\Delta t}\left(
\left. \bar{s}_{rz} \right.\rvert_{0} + \Delta t \left( p + \check{r}_{sf
  \rightarrow rz} - e_{p} \right) - s_{rzmax} \right)\right)$
3. Test for saturation. If $f\left(0,\check{r}_{rz \rightarrow uz}\right) \geq
   0$ then goto 4 else goto 5
4. Saturated. Set $\left. \bar{s}_{sz}\right.\rvert_{\Delta t} = 0$ and
$\hat{r}_{rz \rightarrow uz} = \frac{1}{\Delta t}\left(
\left. \bar{s}_{sz}\right.\rvert_{0} + \Delta t \left(
\frac{w^{+}}{A}g\left(0,\Theta_{sz}\right) -
\frac{q_{sz}^{-}}{A}\right) - \left. \bar{s}_{uz} \right.\rvert_{0} \right)$,
Goto 7
5. Not saturated: find $\left. \bar{s}_{sz}\right.\rvert_{\Delta t}$ such that 
$f\left(\left. \bar{s}_{sz}\right.\rvert_{\Delta t},\check{r}_{rz \rightarrow
  uz}\right) = 0$. 
6. Set $\hat{r}_{rz \rightarrow uz} = \min\left(\check{r}_{rz \rightarrow uz},\frac{1}{\Delta t} \left(
\left. \bar{s}_{sz} \right.\rvert_{\Delta t} + \frac{\Delta t}{T_d} -
 \left. \bar{s}_{uz} \right.\rvert_{0}\right)\right)$.
7. Compute $\hat{r}_{sf \rightarrow rz} = \min\left(\check{r}_{sf \rightarrow
  rz}, \frac{1}{\Delta t}\left( s_{rzmax} - 
\left. \bar{s}_{rz} \right.\rvert_{0} - \Delta t \left( p - e_p - \hat{r}_{rz
  \rightarrow uz} \right) \right)\right)$
8. Solve for $\left. \bar{s}_{uz}\right.\rvert_{\Delta t}$,
$\left. \bar{s}_{rz}\right.\rvert_{\Delta t}$ and
$\left. \bar{s}_{sf}\right.\rvert_{\Delta t}$ using the computed vertical
fluxes.

The first two steps compute the maximum potential downward flux from the
surface and root zones. Steps 3-6 solve saturated zoneand adjust the fluz from
the root zone to the unsaturated zone accordingly. Step 7 adjusts the flux
from the surface zone in the case of upward flow from the unsaturated zone,
with Step 8 using the corrected vertical fluxes to solve for the new values of
the states.

# Transmissivity Profiles

The solution and numerical scheme have been presented with a general
transmissivity function $g\left(\bar{s}_{sz},\Theta_{sz}\right)$. Table
\@ref(tab:hs-transmissivity) present the transmissivity profiles present as options within the `dynatop`
package, the corresponding value to use for the `transmissivity_profile` value
in the model options vector and the additional parameters or properties
required. The additional parameter and properties are defined in Table \@ref(tab:hs-transmissivity-param).

| Name                | $g\left(\bar{s}_{sz},\Theta_{sz}\right)$                                                                                       | Celerity                                                      | $\Theta_{sz}$     |  `transmissivity_profile` value    | Notes                                                        |
| ----                | ----                                                                                                                           | ----                                                        | ----              | ----            | ----                                                         |
| Exponental          | $T_{0}\sin\left(\beta\right)\exp\left(-\frac{\cos\beta}{m}s_{sz}\right)$                                                       | $\frac{\cos\beta}{m}g\left(\bar{s}_{sz},\Theta_{sz}\right)$ | $T_0,\beta,m$ | `"exponential"` | Originally given in [Beven & Freer 2001](https://doi.org/10.1002/hyp.252) |
| Bounded Exponential | $T_{0}\sin\left(\beta\right)\left(\exp\left(-\frac{\cos\beta}{m}s_{sz}\right)
 - \exp\left(-\frac{\cos\beta}{m}D\right)\right)$ | $\frac{cos
   \beta}{m}T_{0}\sin\left(\beta\right)\exp\left(-\frac{\cos\beta}{m}s_{sz}\right)$ | $T_0,\beta,m,D$ | `"bounded_exponential"` | Originally given in [Beven & Freer 2001](https://doi.org/10.1002/hyp.252) |
| Constant Celerity        |    $c_{sz}\left(D-s_{sz}\right)$                     | $c_{sz}$ | $c_{sz},D$ | `"constant"` | |                                                             |
                                                    
  Table: (\#tab:hs-transmissivity) Transmissivity profiles avaiable with the
  `dynatop` package.


| Symbol   | Description                             | unit    |
| ---      | ------                                  | ---     |
| $T_0$    | Transmissiviy at saturation             | m$^2$/s |
| $m$      | Exponential transmissivity constant     | m$^{-1}$   |
| $\beta$  | Angle of hill slope                     | rad     |
| $c_{sz}$ | Saturated zone celerity                 | m/s     |
| $D$      | Depth at which zero lateral flow occurs | m        |

  Table: (\#tab:hs-transmissivity-param) Additional paraemters used in the transmissivity profiles.
