---
title: "The Dynamic TOPMODEL equations"
output: 
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_depth: 2
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{TheNumerical Solution of Dynamic TOPMODEL}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
#output: rmarkdown::html_vignette
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `dynatop` package represents an implimentation of the concepts behind a dynamic TOPMODEL.
One of the underlying principles of dynamic TOPMODEL is that the landscape can be broken up into
hydrologically similar regions, or Hydrological Similarity Units (HSUs), where
all the area within a HSU behaves in a hydrologically similar fashion.

While a Hydrological Similarity Unit (HSU) has typically been thought of as an
area of hillslope with, for example, simliar topgraphic, soil and upslope area
characteristics the idea may be generalised. In doing this a catchments is
concpetualised as a collection of HSUs of different type (e.g. hill slope,
channel, lake) which exchange fluxes at specified levels (e.g. saturated zone,
surface)

As well as the exchange of fluxes this documents considers two types of HSU. The first termed
"hill slope" solves the surface, root, unsaturated and saturated zones
for 'similar' areas of hill slope the catchment a each time step.
The second termed "channel" represents a length of river channel in a
simplified manner allowing the extraction of the inflow from the hillslope. 

The solutions outlined below take an operator splitting approach allow
sequential solution of the HSUs and processes with the HSUs. In doing this the
choice has been made to represent the exchange of fluxes between and within
HSUs as volumes (integrals of the flux over the timestep).

# Notation and nomenclature

The notation used can be broken down as follows. Table \@ref(tab:exchange-notation) outlines the notation used for describing a fluxes exchanged between HSUs. These variables are common across all HSUs.
Table \@ref(tab:hs-notation) outlines the notation used for describing a hill
slope HSU. 
All other notation is given in Table \@ref(tab:other-notation).

The following conventions are used:

-   All fluxes ($q_{* \rightarrow *}$ and $l_{*}$) are considered to be greater or
	equal to zero.

-   Superscript notation $^{\left[i\right]}$ indicates the property of
    the $i$th HSU

-   $\left.x\right\rvert_t$ indicates the value of the
    variable $x$ at time $t$
	
-	Where intermediate evaluations of some variables are compute these are distinguish by use of $\tilde{}$. For example
	$\tilde{s}_{rz}$ is an intermediate value in the computation of
	$s_{rz}$.

	
| Quantity type            | Symbol                      | Description                                              | unit            |
| ---                      | :---:                       | ---                                                      | :---:           |
| Lateral fluxes from HSUs | $l_{sf}$                    | Total lateral flux from surface store                    | (m$^3$/s)/m$^2$ |
|                          | $l_{sz}$                    | Total lateral flux from saturated zone store             | (m$^3$/s)/m$^2$ |
| Other HSU properties     | $f^{\left[k,j\right]}_{sf}$ | Fraction of $l_{sf}$ going from $j$th HSU to $k$th HSU   | -               |
|                          | $f^{\left[k,j\right]}_{sz}$ | Fraction of $l_{sz}$ going from $j$ th HSU to $k$ th HSU | -               |
                                                    
Table: (\#tab:exchange-notation) Outline of notation for describing the exchange between HSUs

	
| Quantity type | Symbol   | Description              | unit  |
| ---           | :---:    | ------                      | :---: |
| Storage       | $s_{sf}$ | Surface excess storage   | m     |
|               | $s_{rz}$ | Root zone storage        | m     |
|               | $s_{uz}$ | Unsaturated zone storage | m     |
|               | $s_{sz}$ | Saturated zone storage deficit| m |
|  Vertical fluxes within HSU  |             $q_{sf \rightarrow rz}$  |       Flow from the surface excess store to the root zone |   (m$^3$/s)/m$^2$|
|                              |             $q_{rz \rightarrow uz}$      |   Flow from the root zone to the unsaturated zone |  (m$^3$/s)/m$^2$|
|                              |             $q_{rz \rightarrow sf}$      |   Flow from the root zone to the surface  excess storage   |   (m$^3$/s)/m$^2$ |
|                              |             $q_{uz \rightarrow sz}$      |   Flow from unsaturated to saturated zone    |   (m$^3$/s)/m$^2$ |                       
|                              |             $q_{sz \rightarrow sf}$      |   Flow from saturated zone to surface excess storage        |   (m$^3$/s)/m$^2$|
|  Other HSU properties        |                       a             |        Area                                    |          m$^2$|
|                              |                  $q_{sfmax}$          |      Maximum flow rate from surface excess to root zone  |   (m$^3$/s)/m$^2$|
|                              |                  $s_{rzmax}$          |      Maximum root zone storage                 |         m|
|                              |                     $T_d$            |       Unsaturated zone time constant per m of saturated storage deficit. |     s/m|
|                              |                   $l_{szmax}$         |      Maximum lateral flux from saturated zone    |  (m$^3$/s)/m$^2$  |
|                              |                   $T_{sf}$            |      Surface excess storage time constant       |        s|
|                              |                      $m$             |       Exponential transmissivity constant       |         -|
|                              |                  $\Delta x$          |       Effective length of the hillslope HSU     |         m|
                                                    
  Table: (\#tab:hs-notation) Outline of notation for describing hill slope
  HSU



| Symbol                              | Description                                                   | unit |
|:-----------------------------------:|---------------------------------------------------------------|:----:|
| $\Delta t$                          | Timestep                                                      | s    |
| $p$                                 | Precipitation rate                                            | m/s  |
| $e_p$                               | Potential evapotranspiration rate                             | m/s  |
| $\mathcal{S}^{\left[i\right]}_{sf}$ | The set of values $j$ for which $f_{sf}^{\left[i,j\right]}>0$ | -    |
| $\mathcal{S}^{\left[i\right]}_{sz}$ | The set of values $j$ for which $f_{sz}^{\left[i,j\right]}>0$ | -    |
  
  Table: (\#tab:other-notation) External inputs to HSUs



# Order of HSUs and the exchange of fluxes

Fluxes between the HSUs occur at two levels, the surface ($l_{sf}$) and the
saturated zone ($l_{sz}$). 
If all the lateral flux from an HSU is redirected to HSUs within the catchment then
\[
\sum\limits_{j} f^{\left[j,i\right]}_{sf} =
    \sum\limits_{k} f^{\left[k,i\right]}_{sz} =1
\]

The total incoming flux to the $i$th HSU expressed in $m^3/s$ is for each
level given by

\[
\sum_{j \in \mathcal{S}^{\left[i\right]}_{*}} f_{*}^{\left[i,j\right]}a^{\left[j\right]}
l^{\left[j\right]}_{*}
\] 

Over a time step $\Delta t$ the volume of the incoming flux in $m^3$ is

\[
\sum_{j \in \mathcal{S}^{\left[i\right]}_{*}} f_{*}^{\left[i,j\right]} a^{\left[j\right]}
\int_{\Delta t}l^{\left[j\right]}_{*}dt
\]


The solutions proposed for the individual HSUs are limited to the situation
that the HSUs can be ordered for each level so when solved in sequence the input fluxes from other HSUs (as given above) are known.

# Hill Slope HSU

The numerical solution implemented in the dynamic TOPMODEL code is based
on solving the ODE(s) governing the evolution of each of the stores in the
HSUs sequentially while approximating the flux between them.

The following sections present the solutions to the governing equations
in the order they are currently solved in the code for given time
step $\Delta t$ (seconds) starting at time $t$ over which the input fluxes ($p$ and $e_p$) are
taken to be constant.

## Step 1: Surface excess redistribution

For the $i$th hill slope HSU the alteration of the surface excess store is
given by
\[
\frac{ds^{\left[i\right]}_{sf}}{dt} =  
    \sum\limits_{j \in \mathcal{S}_{sf}^{\left[i\right]}} f^{\left[i,j\right]}_{sf}\frac{a^{\left[j\right]}}{a^{\left[i\right]}}l^{\left[j\right]}_{sf}
    - l^{\left[i\right]}_{sf}
    + q^{\left[i\right]}_{sz \rightarrow sf}
	+ q^{\left[i\right]}_{rz \rightarrow sf}
    - q^{\left[i\right]}_{sf \rightarrow rz}
\]

The solution of this is approximated through two stages. 
The first stage computes the lateral flux $l^{\left[i\right]}_{sf}$ from the HSU based on the storage at
the start of the time step; ignoring the potential
vertical flux within the HSU. 
The second stage, carried out in Step 5 corrects for the vertical fluxes.

The computation of the lateral flux from the surface excess storage is based on two assumption

1.   There are minimal non-linearities so the surface excess store of a hill slope HSU can be treated as linear tanks with
$l^{\left[i\right]}_{sf} = \frac{1}{T^{\left[i\right]}_{sf}} s^{\left[i\right]}_{sf}$.
2.   The inflow is approximatley constant during the timestep.

Under these assumptions we write
\[
\frac{d\tilde{s}_{sf}}{dt} = \frac{1}{\Delta t} \sum\limits_{j \in \mathcal{S}_{sf}^{\left[i\right]}} f^{\left[i,j\right]}_{sf}\frac{a^{\left[j\right]}}{a^{\left[i\right]}} \int_{\Delta t}l^{\left[j\right]}_{sf}dt
- \frac{1}{T_{sf}^{\left[i\right]}} \tilde{s}
\quad \left. \tilde{s}_{sf} \right\rvert_{t} = \left. s_{sf} \right\rvert_{t}
\]

which can be solved to give
\[
\left. \tilde{s}_{sf} \right\rvert_{t+\Delta t} =
\left. s_{sf}^{\left[i\right]}\right\rvert_{t}
\exp\left(-\frac{\Delta t}{T_{sf}^{\left[i\right]}}\right)
+ \left(1 - \exp\left(-\frac{\Delta t}{T_{sf}^{\left[i\right]}}\right)\right)
\frac{T_{sf}^{\left[i\right]}}{\Delta t} \sum\limits_{j \in \mathcal{S}_{sf}^{\left[i\right]}} f^{\left[i,j\right]}_{sf}\frac{a^{\left[j\right]}}{a^{\left[i\right]}} \int_{\Delta t}l^{\left[j\right]}_{sf}dt
\]

Mass balance gives
\[
 \int_{\Delta t}l^{\left[i\right]}_{sf}dt 
 = \left. s_{sf}^{\left[i\right]}\right\rvert_{t}
 - \left. \tilde{s}_{sf}\right\rvert_{t+\Delta t}
+ \sum\limits_{j \in \mathcal{S}_{sf}^{\left[i\right]}} f^{\left[i,j\right]}_{sf}\frac{a^{\left[j\right]}}{a^{\left[i\right]}} \int_{\Delta t}l^{\left[j\right]}_{sf}dt
 \]

## Step 2: Root Zone

For a single HSU
\[
\frac{ds_{rz}}{dt}=p + q_{sf \rightarrow rz}
-\frac{s_{rx}}{s_{rzmax}}e_{p}-q_{rz \rightarrow sf} - q_{rz \rightarrow uz}
\]
Assuming all the water in the surface excess store is available to the root
zone so long as $q_{sf \rightarrow rz} \leq q_{sfmax}$ the integral of the
flow from the surface excess store can be approximated by
\[
\int\limits_{\Delta t} q_{sf \rightarrow rz} dt =
\min\left(q_{sfmax}\Delta t,\left.\tilde{s}_{sf}\right.\rvert_{t+\Delta t}\right)
\]
Using this and assuming constant precipitation and potential
evapotranspiration rates over the time step the root zone is solved as a two step process. Firstly the ODE
\[
\frac{d\tilde{s}_{rz}}{dt} = p
+ \frac{1}{\Delta t}\int\limits_{\Delta t} q_{sf \rightarrow rz} dt
- \frac{e_{p}}{s_{rzmax}}\tilde{s}_{rz} \quad
\left. \tilde{s}_{rz}\right\rvert_{t} = \left. s_{rz}\right\rvert_{t}
\]
is solved to give
\[
\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} = 
\left. s_{rz}\right\rvert_{t} \exp\left(-\frac{e_{p}}{s_{rzmax}}\Delta
t\right)
+ \left(p
+ \frac{1}{\Delta t}\int\limits_{\Delta t} q_{sf \rightarrow rz} dt \right)
\frac{s_{srmax}}{e_p}
\left(1 - \exp\left(-\frac{e_{p}}{s_{rzmax}}\Delta t\right)\right)
\]
which is the root zone storage not allowing for losses to the surfce excess
store or unsaturated zone. From this
\[
\left. s_{rz}\right\rvert_{t + \Delta t} =
\min\left(\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t}, s_{rzmax}\right)
\]
and the total water passed from the root zone is
\[
\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} -
\left. s_{rz}\right\rvert_{t + \Delta t}
\]

The water passed from the root zone can be passed either to the surface excess
storage or the unsaturated zone. If $\left. s_{sz}\right\rvert_{t} = 0$ the
flux from the root zone is passed to the
surface excess store giving 
\[
\int_{\Delta t} q_{rz \rightarrow sf} dt =
\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} -
\left. s_{rz}\right\rvert_{t + \Delta t}
\quad
\int_{\Delta t} q_{rz \rightarrow uz} dt = 0
\]

If $\left. s_{sz}\right\rvert_{t} > 0$ then the flux from the root zone is
passed to the unsaturated zone store by taking
\[
\int_{\Delta t} q_{rz \rightarrow sf} dt = 0
\quad
\int_{\Delta t} q_{rz \rightarrow uz} dt =
\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} -
\left. s_{rz}\right\rvert_{t + \Delta t}
\] 

## Step 3: Unsaturated Zone

For a single HSU the unsaturated zone representation of a non-linear tank whose time
constant is dependent upon the saturation deficit:
\[
\frac{ds_{uz}}{dt}=q_{rz \rightarrow uz}-\frac{s_{uz}}{s_{sz}T_{d}}
\]

In keeping with the root zone the
solution to the governing ODE is approximated by
\[
\frac{d\tilde{s}_{uz}}{dt} =
\frac{1}{\Delta t}\int_{\Delta t} q_{rz \rightarrow uz} dt
- \frac{\tilde{s}_{uz}}{\left.s_{sz}\right\rvert_{t}T_{d}} \quad
\left.\tilde{s}_{uz}\right\rvert_{t} = \left.s_{uz}\right\rvert_{t}
\]

which is given by 
\[
\left.\tilde{s}_{uz}\right\rvert_{t+\Delta t} =
\left.s_{uz}\right\rvert_{t}\exp\left(-\frac{\Delta
  t}{\left.s_{sz}\right\rvert_{t}T_d}\right)
+ \frac{1}{\left.s_{sz}\right\rvert_{t}T_{d}\Delta t}
\int_{\Delta t} q_{rz \rightarrow uz} dt
 \left(1 -
 \exp\left(-\frac{\Delta t}{\left. s_{sz}\right\rvert_{t}T_{d}}\right)\right)
\]
Mass balance then gives
\[
\int_{\Delta t} q_{uz \rightarrow sz} dt =  \left.s_{uz}\right\rvert_{t} + \int_{\Delta t}
q_{rz \rightarrow uz} dt - \left.\tilde{s}_{uz}\right\rvert_{t+\Delta t}
\]

The above solution ensures that $\left.\tilde{s}_{uz}\right\rvert_{t+\Delta t}$
equals 0 if $\left.s_{sz}\right\rvert_{t}=0$. However to ensure that
$\left.s_{uz}\right\rvert_{t+\Delta t} =0$ if $\left.s_{sz}\right\rvert_{t+\Delta
  t}=0$ the estimate $\left.\tilde{s}_{uz}\right\rvert_{t+\Delta t}$ is revised
  after computation of the saturated zone in Step 5.
  
## Step 4: Saturated Zone

### General Solution

For a hill slope HSU the change in saturated zone storage deficit is
evaluated using a kinematic wave approximation.
For an infinitesimal slab
\[
\frac{dA}{dt} + \frac{dQ}{dx} -r = 0
\]
where $A$, $Q$ and $r$ are the cross sectional flow area, lateral flow and
recharge for the infinitesimal slab.

Consider the HSU to be a rectangle of area $a$ with inflow and outflow
occuring at parallel edges seperated by a distance $\Delta x$ giving an
effective width if $w=\frac{a}{\Delta x}$. Taking a height
$h$ gives $A = hw$. Further noting that $h=h_0-z$ for some
datum $h_0$ and storage deficit $z$ (expressed as a length) gives
\[
\frac{dA}{dt} = w\frac{dh}{dt}=-w\frac{dz}{dt}
\]

The storage deficit $z$ and $Q$ are linked by a one-to-one montotonically
decreasing, continuously differentiable function 
$g: \mathcal{R}\rightarrow \mathcal{R}^{+}$ which returns the lateral flow on
a unit width such that $Q = w g\left(z\right)$.
This relationships can be used to express the change in deficit over time in
terms of lateral flow as follows:
\[
\frac{dz}{dt} =  \frac{dz}{dQ}\frac{dQ}{dt} =
=  \frac{1}{w}\left(\frac{d}{dz}g\left(z\right)\right)^{-1}\frac{dQ}{dt} =
-\frac{1}{w c\left(z\right)}\frac{dQ}{dt}
\]
where $c\left(z\right)=-\frac{d}{dz}g\left(z\right)$ is the kinematic velocity
expressed as a function of lateral flow per unit width.

Subsitution gives
\[
\frac{1}{c\left(z\right)}\frac{dQ}{dt} + \frac{dQ}{dx} -r = 0
\]
to which a numerical solution is sort.

Let $Q^{+}$ and $Q^{-}$ be the lateral flows at the foot and head of the slope
respectivly and $\bar{r}$ a constant inflow per unit length. One possible
four-point or box scheme use a length averaged velocity $\bar{c}$ is given by
\[
\begin{split}
& \left(1-\omega\right)\frac{\left.Q^{-}\right\rvert_{t+1}-\left.Q^{-}\right\rvert_{t}}{\Delta t} +
\omega\frac{\left.Q^{+}\right\rvert_{t+1}-\left.Q^{+}\right\rvert_{t}}{\Delta t} +
\left(1-\theta\right)\left.\bar{c}\right\rvert_{t}
\left(\frac{\left.Q^{+}\right\rvert_{t}-\left.Q^{-}\right\rvert_{t}}{\Delta x} -\left.\bar{r}\right\rvert_{t}\right)
+ \\
& \theta \left.\bar{c}\right\rvert_{t+1} \left(\frac{\left.Q^{+}\right\rvert_{t+1}-\left.Q^{-}\right\rvert_{t+1}}{\Delta x} -\left.\bar{r}\right\rvert_{t+1}\right)
= 0
\end{split}
\]

Taking $\omega=1$ results in the scheme given in the 2001 Dynamic TOPMODEL
paper. In certain conditions \footnote{see Wood, WL "Introduction to Numerical Methods
for Water Resources" Section 4.2 Pg 76-77} it has been shown that this scheme
is unlikely to be numerical stable for all $\Delta t$. An alternate scheme replacing the $\bar{c}$'s with a 'typical' value $\hat{c}$ 
\[
\begin{split}
& \left(1-\omega\right)\frac{\left.Q^{-}\right\rvert_{t+\Delta t}-\left.Q^{-}\right\rvert_{t}}{\Delta t} +
\omega\frac{\left.Q^{+}\right\rvert_{t+\Delta t}-\left.Q^{+}\right\rvert_{t}}{\Delta t} +
\left(1-\theta\right)\hat{c}
\left(\frac{\left.Q^{+}\right\rvert_{t}-\left.Q^{-}\right\rvert_{t}}{\Delta x} - \left.\bar{r}\right\rvert_{t}\right)
+ \\
& \theta \hat{c}\left(\frac{\left.Q^{+}\right\rvert_{t+\Delta t}-\left.Q^{-}\right\rvert_{t+\Delta t}}{\Delta x} - \left.\bar{r}\right\rvert_{t+\Delta t}\right)
= 0
\end{split}
\]
is stable for $\omega \geq 0.5$, $\theta \geq 0.5$.

Rearranging this and taking 
\[
\lambda = \frac{\hat{c}\Delta t}{\Delta x}
\]
gives

\[
\begin{split}
  \left( \omega + \theta \lambda \right) &
  \left.Q^{+}\right\rvert_{t+\Delta t} +
  \left(1 - \omega - \theta \lambda \right) \left. Q^- \right\rvert_{t+\Delta t} \\
  & - \left( \omega - \left(1-\theta\right)\lambda \right) \left.Q^{+}\right\rvert_{t}
  - \left(1 - \omega + \left(1 - \theta\right)\lambda \right) \left. Q^- \right\rvert_{t}
\\
& - \lambda \Delta x \left( \left(1-\theta\right)\left.\bar{r}\right\rvert_{t}
+ \theta\left.\bar{r}\right\rvert_{t+\Delta t}\right)=0
\end{split}
\]

Two futher complication arise in applying the above equation. The first is
the effect of saturation at $z=0$ which limits the lateral flow to 
$Q\leq wg\left(0\right)$ at all points and times by producing
return flow to the surface excess store. In applying the above numerical
scheme to a given HSU below this limit is applied to the fluxes transfered to and from the HSU.

The second complication is the estimatation of $\hat{c}$. Since $z$ and $Q$
have a one-to-one relationship we consider that $\hat{c}$ can be thought of as
a function of the flow rates, including $\bar{r}$. The recharge $\bar{r}$ must
be included else the $Q^{+}$ will not alter for areas of hillslope with
inflows (e.g. the top of hillslopes). 

Assuming the saturated zone lies
parallel to the surface with gradient $\tan\beta$  and $\bar{r}$ arrives
in the vertical plane as estimate of the contribution of $\bar{r}$ to the
downslope flow rate si given by $\bar{r}\sin\beta$. The estimate is $\hat{c}$
is then based on averaging the available values to give
\[
\bar{Q} =
\frac{1}{3}\left(\left.Q^{+}\right\rvert_{t} +
\left.Q^{-}\right\rvert_{t} + \left.\bar{r}\right\rvert_{t}\sin\beta 
\left.Q^{-}\right\rvert_{t+\Delta t} + \left.\bar{r}\right\rvert_{t+\Delta t}\sin\beta 
\right)
\]

#### Example: Exponential Transmissivity Profile

Within the kinematic solution for the saturated zone there is the presumption
of a relationship between $Q$ and $z$. In the case of the exponential
transmissivity profile we get
\[
g\left(z\right) = T_{0}\sin\beta\exp\left(-\frac{z}{m}\cos\beta\right)
\]
and
\[
c\left(z\right) = -\frac{d}{dz} T_{0}\sin\beta\exp\left(-\frac{z}{m}\cos\beta\right)
= T_{0}\sin\beta\frac{\cos\beta}{m}\exp\left(-\frac{z}{m}\cos\beta\right)
= \frac{\cos\beta}{m}g\left(z\right) = \frac{\cos\beta}{m}\frac{Q}{w}
\]
The estimate of $\hat{c}$ is thus
\[
\hat{c} = \frac{\cos\beta}{m}g\left(z\right) = \frac{\cos\beta}{m}\frac{\bar{Q}}{w}
\]

### Application within the model
Consider the $i$th HSU and converting to flow per unit plan area gives the maximum lateral flux as 
\[
l^{\left[i\right]}_{szmax}=\frac{w^{\left[i\right]}g^{\left[i\right]}\left(0\right)}{a^{\left[i\right]}}
=\frac{g^{\left[i\right]}\left(0\right)}{\Delta x^{\left[i\right]}}
\]
For $l^{\left[i\right]}_{szmaz} \geq l_{sz}^{\left[i\right]}\geq 0$
the outflow from the saturated zone as
\[
Q^+ = a^{\left[i\right]}l^{\left[i\right]}_{sz}
\]
The inflow is made up the sum of fractional outflow from upslope HSUs, the sum
of which may be greater then the maximum lateral flux. Noting this and that
the inflow from the other HSUs is represented as a volume take
\[
\left.Q^{-}\right\rvert_{t} =
\left.Q^{-}\right\rvert_{t+\Delta t} =
a^{\left[i\right]} l^{\left[i\right]}_{szin} =
a^{\left[i\right]} \min\left(\frac{1}{\Delta t}
\sum_{j}f_{sz}^{\left[i,j\right]}\frac{a^{\left[j\right]}}{a^{\left[i\right]}}\int_{\Delta
  t}l^{\left[j\right]}_{sz} dt,
l_{szmax}^{\left[i\right]}\right)
\]

Since the recharge is also represented as a volume over the whole hillslope
take
\[
\left.\bar{r}\right\rvert_{t+\Delta t} =
\left.\bar{r}\right\rvert_{t} =
\frac{a^{\left[i\right]}}{\Delta x^{\left[i\right]} \Delta t}
\int_{\Delta t} q_{uz\rightarrow sz} dt
\]

Subsitution gives an initial unconstrained estimate of the lateral flux from the saturated zone at the end of
the time step $\left.\tilde{l}^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t}$
as

\[
\left( \omega + \theta \lambda^{\left[i\right]} \right)
\left.\tilde{l}^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t} =
\left( \omega - \left(1-\theta\right)\lambda^{\left[i\right]} \right)
\left.l^{\left[i\right]}_{sz}\right\rvert_{t} +
\lambda^{\left[i\right]}\left( l^{\left[i\right]}_{szin} + 
\frac{1}{\Delta t} \int_{\Delta t} q^{\left[i\right]}_{uz\rightarrow sz} dt \right)
\]

Assuming $\hat{c}^{\left[i\right]}$ and hence $\lambda^{\left[i\right]}$ is not dependent upon
$\left.\tilde{l}^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t}$ then this
leads a simple solution for
$\left.l^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t}$
as
\[
\left.l^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t} = \min\left(
\left.\tilde{l}^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t},
l^{\left[i\right]}_{szmax}\right)
\]

### Determining the storage deficit

The above scheme determines the flows at the head and foot of the HSU at
descrete times. Linearly approximating between the time points gives
\[
\int_{\Delta t} l_{sz} dt = \frac{\Delta t}{2} \left(
\left.l_{sz}\right\rvert_{t+\Delta t} + \left.l_{sz}\right\rvert_{t}\right)
\]
From this
\[
\tilde{s}_{sz} =
\left.s^{\left[i\right]}_{sz}\right\rvert_{t} + \int_{\Delta t}
l^{\left[i\right]}_{sz} dt
- \sum_{j}f_{sz}^{\left[i,j\right]}\frac{a^{\left[j\right]}}{a^{\left[i\right]}}\int_{\Delta t}
l^{\left[j\right]}_{sz} dt
- \int_{\Delta t} q^{\left[i\right]}_{uz\rightarrow sz} dt
\]
from which can be computed 
\[
\left.s^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t} =
\max\left(0,\tilde{s}_{sz}\right)
\] and
\[
\left.\int_{\Delta t} q^{\left[i\right]}_{sz\rightarrow sf} dt \right\rvert_{t+\Delta t} =
\left.s^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t} - \tilde{s}_{sz}
\]





The values of $\bar{c}$ are themseleves typical velocity values over the length
of the HSU at a given time. One method of computing these is is treat
$s_{sz}$ as a typical value of $z$ and take
\[
\bar{c} = c\left(s_{sz}\right)
\]
This representation of $\bar{c}$ can be evaluated at time $t$, but not a time
$t+\Delta t$. However if the $c\left(z\right)$ is montonically increasing as
$z$ decreases (i.e. velocities increase as saturation increases) then
\[
c\left(\left.s_{sz}\right\rvert_{t+\Delta t}\right) \leq
c\left(\left.\check{s}_{sz}\right\rvert_{t+\Delta t}\right)
\]
where
\[
\left.\check{s}_{sz}\right\rvert_{t+\Delta t} =
\max\left(0,
\left.s_{sz}\right\rvert_{t} - l_{szin}\Delta t  - \int_{\Delta t} q^{\left[i\right]}_{uz\rightarrow sz} dt\right)
\]

It is therefor proposed to use the estimate 
\[
\hat{c} = \frac{1}{2}\left(
c\left(\left.s_{sz}\right\rvert_{t}\right) +
c\left(\left.\check{s}_{sz}\right\rvert_{t+\Delta t}\right)
\right)
\]

## Step 5: Correcting vertical stores

Having evaluated the stores in the direction of gravity there is the need to
correct for vertical fluxes returning water to the surface thus increase
$s_{sf}$.

If saturation has occured, that is 
$\left. s_{sz}\right. \rvert_{t+\Delta t}=0$, 
then there can be no water stored in the unsaturated zone. Let
\[
\int_{\Delta t} q_{uz \rightarrow sf}dt = \left\{ \begin{array}{cc}
  \left.\tilde{s}_{uz}\right. \rvert_{t+\Delta t} &
  \left. s_{sz}\right. \rvert_{t+\Delta t}=0\\
  0 & \mathrm{otherwise}
\end{array}
\right.
\]

The correction of the stores then takes the form
\[
\left. s_{sf} \right. \rvert_{t+\Delta t} =
\left.\tilde{s}_{sf}\right. \rvert_{t+\Delta t}  + \int_{\Delta t} q_{rz
  \rightarrow sf} dt + \int_{\Delta t} q_{sz \rightarrow sf} dt + \int_{\Delta t} q_{uz \rightarrow sf} dt
\]
and 
\[
\left. s_{uz} \right. \rvert_{t+\Delta t} =
\left.\tilde{s}_{uz}\right. \rvert_{t+\Delta t} - \int_{\Delta t} q_{uz
  \rightarrow sf} dt
\]


# Channel HSU

The current implimentation of the channel HSU calculates the average discharge
to the channel over the time step in $m^3/s$. This is given for the $k$ th channel HSU as
\[
\frac{1}{\Delta t} \left(
\sum\limits_{j}
f^{\left[k,j\right]}_{sf}a^{\left[j\right]}l^{\left[j\right]}_{sf} +
\sum\limits_{j}
f^{\left[k,j\right]}_{sz}a^{\left[j\right]}l^{\left[j\right]}_{sz} \right) + p
\]

# Appendix: Single variable non-homogeneous ODE with constant input

The initial condition
problem$$\frac{dx\left(t\right)}{dt} = a - b x\left(t\right) \quad x\left(0\right) = x_0$$
or more compactly
$$x^{\prime}\left(t\right) = a - b x\left(t\right) \quad x\left(t_0\right) = x_0$$
involves the solution of first order linear system. This can be solved
explicitly using an ‘integrating factor’. Let
$\mu = \exp\left(\int\limits_t b dt\right) = \exp\left(bt\right)$.
Multiplying both sides by $\mu$ then integrating (noting the LHS is the
result of the product formula in differentiation) gives
$$\exp\left(bt\right) x = \int\limits_{t} a\exp\left(bt\right) dt = \frac{a}{b}\exp\left(bt\right) + K$$
The constant $K$ can be evaluates using the initial conditions as
$K=x_{0}-\frac{a}{b}$. Substitution and rearrangement then gives
$$x = x_{0}\exp\left(-bt\right) + \frac{a}{b}\left(1-\exp\left(-bt\right)\right)$$
Note that $$\begin{array}{c}
        x\rightarrow0 \quad\mathrm{as}\quad b\rightarrow\infty\\
        x\rightarrow x_{0} + at \quad\mathrm{as}\quad b\rightarrow0\\
    \end{array}$$


<!-- # Appendix: A four point solution for the exponential transmissivity profile -->

<!-- Ignoring the use of a "typical" value $\hat{c}$ we can write the four point -->
<!-- solution as -->
<!-- \[ -->
<!-- \begin{split} -->
<!--   \left( \omega + \theta \left.\lambda\right\rvert_{t+\Delta t} \right) & -->
<!--   \left.Q^{+}\right\rvert_{t+\Delta t} + -->
<!--   \left(1 - \omega - \theta \left.\lambda\right\rvert_{t+\Delta t} \right) \left. Q^- \right\rvert_{t+\Delta t} \\ -->
<!--   & - \left( \omega - \left(1-\theta\right)\left.\lambda\right\rvert_{t} \right) \left.Q^{+}\right\rvert_{t} -->
<!--   - \left(1 - \omega + \left(1 - \theta\right)\left.\lambda\right\rvert_{t} \right) \left. Q^- \right\rvert_{t} -->
<!-- \\ -->
<!-- & - \Delta x \left( \left(1-\theta\right)\left.\lambda\right\rvert_{t}\left.\bar{r}\right\rvert_{t} -->
<!-- + \theta\left.\lambda\right\rvert_{t+\Delta t}\left.\bar{r}\right\rvert_{t+\Delta t}\right)=0 -->
<!-- \end{split} -->
<!-- \] -->

<!-- Treating all the terms at time $t$ as known this gives -->

<!-- \[ -->
<!-- \begin{split} -->
<!--   \left( \omega + \theta \left.\lambda\right\rvert_{t+\Delta t} \right) & -->
<!--   \left.Q^{+}\right\rvert_{t+\Delta t} + -->
<!--   \left(1 - \omega - \theta \left.\lambda\right\rvert_{t+\Delta t} \right) \left. Q^- \right\rvert_{t+\Delta t} \\ -->
<!--   & - \Delta x\theta\left.\lambda\right\rvert_{t+\Delta t}\left.\bar{r}\right\rvert_{t+\Delta t} -->
<!--   - K = 0 -->
<!-- \end{split} -->
<!-- \] -->
<!-- Treating the estimate of the kinematic velocity to be based on -->
<!-- the outflow gives -->
<!-- \[ -->
<!-- \left.\lambda\right\rvert_{t+\Delta t} = \frac{\cos \beta}{w m} \left.Q^{+}\right\rvert_{t+\Delta t} -->
<!-- \] -->

<!-- Rearrangement provides a quadratic in the unknown -->
<!-- $\left.Q^{+}\right\rvert_{t+\Delta t}$ -->
<!-- \[ -->
<!-- \theta  \frac{\cos \beta}{w m} \left.Q^{+}\right\rvert_{t+\Delta t}^2 -->
<!-- +\left(\omega - \theta \frac{\cos \beta}{w m}\left( -->
<!-- \left. Q^- \right\rvert_{t+\Delta t} +  \Delta -->
<!-- x\left.\bar{r}\right\rvert_{t+\Delta t}\right )\right) -->
<!-- \left.Q^{+}\right\rvert_{t+\Delta t} -->
<!-- + \left(1 - \omega\right)\left. Q^- \right\rvert_{t+\Delta t}-K = 0 -->
<!-- \] -->

<!-- The roots of this quadratic can be found using standard formulea, however the -->
<!-- challange reamins in selecting the appropriate root. This can be avoided by -->
<!-- choice of $\omega=\theta=1$ which results in only one of the possible roots -->
<!-- being valid. -->
