---
title: "Towards a better Numerical Solution of Dynamic TOPMODEL"
output: 
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_depth: 2
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{Towards a better Numerical Solution of Dynamic TOPMODEL}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
#output: rmarkdown::html_vignette
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

** This is a working document outlining the improved numerical solution for Dynamic TOPMODEL**

The dynamic TOPMODEL R package implements a set of numerical solutions to the
governing equations of the dynamic TOPMODEL formulation. This vignette
documents the formulation and the numerical solutions used for the "hill slope" elements.

# Notation and nomenclature

Consider two types of Hydrological response unit (HRU). The first termed
"hill slope" solves the surface, root, unsaturated and saturated zones
for 'similar' areas of the catchment a each time step.
Table \@ref(tab:hru-notation) outlines the notation used for describing a
"hill slope" HRU.


  Quantity type                                   Symbol                 Description                                                                 unit
  ------------------------------------ -----------------------------     -------------------------------------------------------------------- -----------------
  Storage                                        $s_{ex}$                Surface excess storage                                                       m
                                                 $s_{rz}$                Root zone storage                                                            m
                                                 $s_{uz}$                Unsaturated zone storage                                                     m
                                                 $s_{sz}$                Saturated zone storage deficit                                               m
  Vertical fluxes within HRU                     $q_{rz \rightarrow uz}$ Flow from the root zone to the unsaturated zone                        (m$^3$/s)/m$^2$
                                                 $q_{rz \rightarrow ex}$ Flow from the root zone to the surface excess storage                  (m$^3$/s)/m$^2$  
                                                 $q_{uz}$                Flow from unsaturated to saturated zone                                (m$^3$/s)/m$^2$
                                                 $q_{sz}$                Flow from saturated zone to surface excess storage                    (m$^3$/s)/m$^2$
  Lateral down slope fluxes from HRU             $l_{ex}$                Total lateral flux from surface excess                                (m$^3$/s)/m$^2$
                                                 $l_{sz}$                Total lateral flux from saturated zone                                (m$^3$/s)/m$^2$
  Other HRU properties                               a                   Area                                                                        m$^2$
                                        $w^{\left[i,j\right]}_{ex}$      fraction of $l_{ex}$ going from $j$th to $i$th HRU                            -
                                        $w^{\left[i,j\right]}_{sz}$      fraction of $l_{sz}$ going from $j$th to $i$th HRU                            -
                                                $s_{rzmax}$              maximum root zone storage                                                     m
                                                   $T_d$                 Unsaturated zone time constant per m of saturated storage deficit.           h/m
                                                 $l_{szmax}$             Maximum lateral flux from saturated zone                              (m$^3$/s)/m$^2$         
                                                 $T_{ex}$                Surface excess storage time constant                                          h
                                                    $m$                  Exponential transmissivity constant                                           -     -

  Table: (\#tab:hru-notation) Outline of notation for describing "hill slope"
  HRUs

The second, termed "channel" represents a length of river
channel. This document is concerned only with the computation of the inflow to
the channel. It does not deal with the routing of the
water within the channel. As such it considers the channel HRUs to act as a sink collecting water from the
"hill slope" 
HRUs over the course of a time step. Table \@ref(tab:ch-notation) outlines
the notation for channel HRU.

                                   Symbol              Description                                                                 unit
  ---------------------- ----------------------------- -------------------------------------------------------------------------- -------
  Storage                          $s_{ch}$            channel storage                                                               m
  Other HRU properties                 a               Area                                                                        m$^2$
                          $f^{\left[k,j\right]}_{ex}$  fraction of $l_{ex}$ going from $j$th hill slope HRU to $k$th channel HRU      -
                          $f^{\left[k,j\right]}_{sz}$  fraction of $l_{sz}$ going from $j$th hill slope HRU to $k$th HRU              -

  Table: (\#tab:ch-notation) Outline of notation for describing "channel"
  HRUs


From the above a mass conservative system will redirect all flows within the
    defined catchment hence:
    $$\sum\limits_{j} w^{\left[j,i\right]} +
    \sum\limits_{k} f^{\left[k,i\right]} =1$$

Inputs to the system are given in Table [tab:inputs]. These are treated as
being the same for every HRU though the calculations readily allow for them to
vary by HRU.

   Symbol  Description                     unit
  -------- ------------------------------ ------
    $p$    Precipitation rate              m/h
   $e_p$   Potential evapotranspiration    m/h

  Table: (\#tab:inputs) Eternal inputs to HRUs

Later we make use of the following:

-   Superscript notation $^{\left[i\right]}$ to indicate the property of
    the $i$th HRU

-   Bold lower case letter to indicate the column vector of quantities from all
    HRUs, e.g.
    $\mathbf{q}_{rz} = \left(q_{rz}^{\left[1\right]},\ldots,q_{rz}^{\left[n\right]}\right)^{T}$

-   Bold uppercase letters to indicate matrices which may be diagonal if
    the underlying variables is a vector (e.g. $\mathbf{A}$ is a
    diagonal matrix of area) or dense (e.g. $W_{sz}$ where the $j$th
    element of the $i$th row is $w_{sz}^{\left[i,j\right]}$). 
	
-	The identity matrix is written as $\mathbf{I}$. The notation $\mathbf{0}$
     is used to indicate a matrix or vector of zeros whose size can be inferred
     from its location.

-   The notation $\left.x\right\rvert_t$ to indicate the value of the
    variable $x$ at time $t$
	
-	To illustrate some calculations intermediate evaluations variables are
     computed. To distinguish these a $\tilde{}$ is used. For example
	 $\tilde{q}_{rz}$ is an intermediate value in the computation of
     $q_{rz}$. In some cases these values may evolve across multiple
     steps. Where needed the superscript $^\left[-\right]$ will be used to
     indicate the value at the start of the step and $^\left[+\right]$ that at
     the end.

# Numerical Solution

The numerical solution implemented in the dynamic TOPMODEL code is based
on solving the ODE(s) governing the evolution of each of the stores in the
HRUs sequentially while approximating the flux between then.

The following sections present the solutions to the governing equations
in the order they are currently solved in the code for given time
step $\Delta t$ (hr) starting at time $t$ over which the input fluxes ($p$ and $e_p$) are
taken to be constant.

## Step 1: Initializing the channel storage
The channel acts as a sink with no outflows. For a single reach:
$$a^{\left[k\right]}\frac{ds^{\left[k\right]}_{ch}}{dt} = 
    \sum\limits_{j} f^{\left[k,j\right]}_{ex}a^{\left[j\right]}l^{\left[j\right]}_{ex}
    + \sum\limits_{j} f^{\left[k,j\right]}_{sz}a^{\left[j\right]}l^{\left[j\right]}_{sz}
    + a^{\left[k\right]}p$$
For all channel reaches this can be written in matrix form as
$$\mathbf{A}_{ch}\frac{d\mathbf{s}_{ch}}{dt} = 
    \mathbf{F}_{ex}\mathbf{A}\mathbf{l}_{ex}
    + \mathbf{F}_{sz}\mathbf{A}\mathbf{l}_{sz}
    + \mathbf{A}_{ch}p$$ 
or equivalently
$$\frac{d\mathbf{s}_{ch}}{dt} = 
    \mathbf{A}^{-1}_{ch}\mathbf{F}_{ex}\mathbf{A}\mathbf{l}_{ex}
    + \mathbf{A}_{ch}^{-1}\mathbf{F}_{sz}\mathbf{A}\mathbf{l}_{sz}
    +p$$

The solution presumes that $\left.\mathbf{s}_{ch}\right\rvert_{t}=\mathbf{0}$
with the integral of each of the summed terms being evaluated individually to
give the total $\left.\mathbf{s}_{ch}\right\rvert_{t+\Delta t}$.
The easiest of these terms to integrate is the precipitation input which gives
\[ \tilde{\mathbf{s}}_{ch} = \mathbf{I}p\Delta t \]

## Step 2: Surface excess redistribution

For the $i$th hill slope HRU the alteration of the surface excess store is
given by
\[ a^{\left[i\right]}\frac{ds^{\left[i\right]}_{ex}}{dt} =  \left(w^{\left[i,i\right]}_{ex}-1\right)a^{\left[i\right]}l^{\left[i\right]}_{ex}
    + \sum\limits_{j \neq i} w^{\left[i,j\right]}_{ex}a^{\left[j\right]}l^{\left[j\right]}_{ex}
    + a^{\left[i\right]}q^{\left[i\right]}_{sz}
	+ a^{\left[i\right]}q^{\left[i\right]}_{rz \rightarrow ex}
	\] 
For all the hill slope HRU this can be expressed as:
$$\mathbf{A}\frac{d\mathbf{s}_{ex}}{dt} =  \left(\mathbf{W}_{ex}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{ex}
    + \mathbf{A}\mathbf{q}_{sz} + \mathbf{A}\mathbf{q}_{rz \rightarrow ex}$$
The surface excess store also passes water to the channel. Let $\mathbf{y}$ be
the contribution to the channel storage from surface excess and 
\[ \mathbf{x} = \left[ \begin{array}{c} \mathbf{s}_{ex} \\
                       \mathbf{y} \end{array}\right] \]
This allows the evolution of $\mathbf{x}$ to be written as
$$
\left[ \begin{array}{cc} \mathbf{A} & \mathbf{0} \\
         \mathbf{0} & \mathbf{A}_{ch} \end{array} \right]
     \frac{d\mathbf{x}}{dt} =
	      \left[ \begin{array}{c} \left(\mathbf{W}_{ex}-\mathbf{I}\right)\mathbf{A} \\
              \mathbf{F}_{ex}\mathbf{A} \end{array}\right]
          \mathbf{l}_{ex} +
          \left[ \begin{array}{cc} \mathbf{A} & \mathbf{0} \\
                   \mathbf{0} & \mathbf{A}_{ch} \end{array} \right]
			   \left[ \begin{array}{c} \mathbf{q}_{sz} + \mathbf{q}_{rz \rightarrow ex} \\
                       \mathbf{0} \end{array}\right]
$$
					   
Assuming that there are minimal non-linearities the surface excess stores of
the hill slope HRUs are taken to be linear tanks with
$l^{\left[i\right]}_{ex} = \frac{1}{T_{ex}} s^{\left[i\right]}_{ex}$

Substitution of the flow storage relationship and rearrangement gives
$$
     \frac{d\mathbf{x}}{dt} =
	 \left[ \begin{array}{cc} \mathbf{A} & \mathbf{0} \\
         \mathbf{0} & \mathbf{A}_{ch} \end{array} \right]^{-1}
	      \left[ \begin{array}{cc}
		  \begin{array}{c} \left(\mathbf{W}_{ex}-\mathbf{I}\right)\mathbf{A}\mathbf{T}^{-1}_{ex} \\
              \mathbf{F}_{ex}\mathbf{A}\mathbf{T}^{-1}_{ex} \end{array} & \mathbf{0} \end{array}
			  \right]
          \mathbf{x} +
			   \left[ \begin{array}{c} \mathbf{q}_{sz} + \mathbf{q}_{rz \rightarrow ex}\\
                       \mathbf{0} \end{array}\right]
$$
	
The solution of this is carried out through two stages. The first
stage redistributes the surface excess storage $\left.\mathbf{s}_{ex}\right\rvert_{t}$ between the
hill slope and channel HRUs on the presumption that there is no inflows
($\mathbf{q}_{sz} + \mathbf{q}_{rz \rightarrow ex} =\mathbf{0}$). The second stage, carried out in later steps
adds the inflow term.

Specifically letting
\[ \tilde{\mathbf{x}} = \left[ \begin{array}{c} \tilde{\mathbf{s}}_{ex} \\
                       \tilde{\mathbf{s}}_{ch} \end{array} \right] \]
the ODE initial condition problem
$$\frac{d\mathbf{x}}{dt}=\left[ \begin{array}{cc} \mathbf{A} & \mathbf{0} \\
         \mathbf{0} & \mathbf{A}_{ch} \end{array} \right]^{-1}
	      \left[ \begin{array}{cc}
		  \begin{array}{c} \left(\mathbf{W}_{ex}-\mathbf{I}\right)\mathbf{A}\mathbf{T}^{-1}_{ex} \\
              \mathbf{F}_{ex}\mathbf{A}\mathbf{T}^{-1}_{ex} \end{array} & \mathbf{0} \end{array}
			  \right]
          \mathbf{x} \quad \mathbf{x}_{0} = \left[\begin{array}{c}
                                                    \left.\mathbf{s}_{ex}\right\rvert_t
\\ \tilde{\mathbf{s}}_{cg}^{\left[-\right]}\end{array}\right]$$ 
is solve using the eigenvalue method to give
$$
\left[\begin{array}{c} \tilde{s}_{ex} \\
\tilde{\mathbf{s}}_{ch}^{\left[+\right]} \end{array}\right]
$$
an intermediate solution to the surface excess and channel storage through the
redistribution of the initial surface excess water.

### Comments

1. The flow to the channel and neighbouring hillslope HRUs is possibly underestimated since the possible flows from the
   saturated zone ($\mathbf{q}_{sz}$) and root zone ($\mathbf{q}_{rz
   \rightarrow ex}$)
   may be positive.
1. The only interaction between the other stores and the surface excess
   are flows to the surface excess. This step could be evaluated later with
   the estimates of these fluxes.

## Step 3: Root Zone

For a single HRU
$$\frac{ds_{rz}}{dt}=p-\frac{s_{rx}}{s_{rzmax}}e_{p}-q_{rz\rightarrow ex} - q_{rz\rightarrow uz}$$
	
The root zone is solved as a two step process. Firstly the ODE
$$\frac{d\tilde{s}_{rz}}{dt}=p-\frac{e_{p}}{s_{rzmax}}\tilde{s}_{rz} \quad  \left. \tilde{s}_{rz}\right\rvert_{t} = \left. s_{rz}\right\rvert_{t}$$
to give $$\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} = 
    \left. s_{rz}\right\rvert_{t} \exp\left(-\frac{e_{p}}{s_{rzmax}}\Delta t\right) + p\frac{ s_{srmax}}{e_p}\left(1 - \exp\left(-\frac{e_{p}}{s_{rzmax}}\Delta t\right)\right)$$
which can be though off as the unconstrained root zone storage. Then
from this
$$\left. s_{rz}\right\rvert_{t + \Delta t} = \min\left(\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t}, s_{rzmax}\right)$$
and the total water passed from the root zone is
$\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} - \left. s_{rz}\right\rvert_{t + \Delta t}$.

The water passed from the root zone can be passed either to the surface excess
storage or the unsaturated zone. If $\left. s_{sd}\right\rvert_{t} = 0$ the
flux from the root zone is passed to the
surface excess store giving a revised estimate of
$$ \tilde{s}_{ex}^{\left[+\right]} =
   \tilde{s}_{ex}^{\left[-\right]} +
 \left.\tilde{s}_{rz}\right\rvert_{t + \Delta t} -
 \left. s_{rz}\right\rvert_{t + \Delta t}$$ 
and $\int_{\Delta t} q_{rz \rightarrow uz} dt = 0$.
If $\left. s_{sd}\right\rvert_{t} > 0$ then the flux from the root zone is
passed to the unsaturated zone store by taking
\[
\int_{\Delta t} q_{rz \rightarrow uz} dt =
\left. \tilde{s}_{rz}\right\rvert_{t + \Delta t} -
\left. s_{rz}\right\rvert_{t + \Delta t}
\] 
and $\int_{\Delta t} q_{rz \rightarrow ex} dt = 0$.

## Step 4: Unsaturated Zone
For a single HRU the unsaturated zone representation of a non-linear tank whose time
constant is dependent upon the saturation deficit:
$$\frac{ds_{uz}}{dt}=q_{rz}-\frac{s_{uz}}{s_{sz}T_{d}}$$

In keeping with that for the root zone is to approximate the
solution to the governing ODE by the solution to
$$\frac{d\tilde{s}_{uz}}{dt}= \frac{1}{\Delta t}\int_{\Delta t} q_{rz} dt - \frac{\tilde{s}_{uz}}{\left.s_{sz}\right\rvert_{t}T_{d}} \quad \left.\tilde{s}_{uz}\right\rvert_{t} = \left.s_{uz}\right\rvert_{t}$$
which is given by 
\[
\left.\bar{s}_{uz}\right\rvert_{t+\Delta t} = 
\left.s_{uz}\right\rvert_{t}\exp\left(-\frac{\Delta
  t}{\left. s_{sz}\right\rvert_{t}T_d}\right)+\frac{1}{\Delta t}\int_{\Delta
  t} q_{rz} dt\left. s_{sz}\right\rvert_{t}T_d\left(1 -
\exp\left(-\frac{\Delta t}{\left. s_{sz}\right\rvert_{t}T_{d}}\right)\right)
\]
Mass balance then gives
\[
\int_{\Delta t} q_{uz} dt =  \left.s_{uz}\right\rvert_{t} + \int_{\Delta t}
q_{rz} dt - \left.\bar{s}_{uz}\right\rvert_{t+\Delta t}
\]

The above solution ensures that $\left.\bar{s}_{uz}\right\rvert_{t+\Delta t}$
equals 0 if $\left.s_{sz}\right\rvert_{t}=0$. However to ensure that
$\left.s_{uz}\right\rvert_{t+\Delta t} =0$ if $\left.s_{sz}\right\rvert_{t+\Delta
  t}=0$ the estimate $\left.\bar{s}_{uz}\right\rvert_{t+\Delta t}$ is revised
  after computation of the saturated zone.
  
## Step 5: Saturated Zone

For the $i$th hill slope HRU the change in saturated zone storage deficit is
given by 
$$a^{\left[i\right]}\frac{ds^{\left[i\right]}_{sz}}{dt} = -a^{\left[i\right]}q^{\left[i\right]}_{uz} - \left(w^{\left[i,i\right]}_{sz}-1\right)a^{\left[i\right]}l^{\left[i\right]}_{sz}
    - \sum\limits_{j \neq i}
    w^{\left[i,j\right]}_{sz}a^{\left[j\right]}l^{\left[j\right]}_{sz}
    + a^{\left[i\right]}q^{\left[i\right]}_{sz}$$ 
For the assumed exponential transmissivity profile:
$$\frac{dl^{\left[i\right]}_{sz}}{dt} = -\frac{l^{\left[i\right]}_{sz}}{m}\frac{ds^{\left[i\right]}_{sz}}{dt}$$
which gives
$$-a^{\left[i\right]}\frac{m}{l^{\left[i\right]}_{sz}}\frac{dl^{\left[i\right]}_{sz}}{dt}
    = -a^{\left[i\right]}q^{\left[i\right]}_{uz} - \left(w^{\left[i,i\right]}_{sz}-1\right)a^{\left[i\right]}l^{\left[i\right]}_{sz}
    - \sum\limits_{j \neq i} w^{\left[i,j\right]}_{sz}a^{\left[j\right]}l^{\left[j\right]}_{sz}
    + a^{\left[i\right]}q^{\left[i\right]}_{sz}$$

The flux $q^{\left[i\right]}_{sz}$ ensures that
$s^{\left[i\right]}_{sz} \geq 0$ and
$l^{\left[i\right]}_{sz} \leq l^{\left[i\right]}_{szmax}$. Thus if
$s^{\left[i\right]}_{sz} = 0$ or
$l^{\left[i\right]}_{sz} = l^{\left[i\right]}_{szmax}$ then
$$a^{\left[i\right]}q^{\left[i\right]}_{sz} = 
    \min\left( a^{\left[i\right]}q^{\left[i\right]}_{uz} + \left(w^{\left[i,i\right]}_{sz}-1\right)a^{\left[i\right]}l^{\left[i\right]}_{sz}
    + \sum\limits_{j \neq i} w^{\left[i,j\right]}_{sz}a^{\left[j\right]}l^{\left[j\right]}_{sz},0\right)$$
but is zero otherwise.

Combining the above equations for all hill Slope HRUs gives
$$\mathbf{A}\frac{d\mathbf{s}_{sz}}{dt} = -\mathbf{A}\mathbf{q}_{uz} - \left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
    + \mathbf{A}\mathbf{q}_{sz}$$ which simplifies to
$$\frac{d\mathbf{s}_{sz}}{dt} = -\mathbf{q}_{uz} - \mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
    + \mathbf{q}_{sz}$$

Substituting the transmissivity relationship gives
$$-\mathbf{L}^{-1}_{sz}\mathbf{M}\frac{d\mathbf{l}_{sz}}{dt} = -\mathbf{q}_{uz} - \mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
    + \mathbf{q}_{sz}$$

The solution of these limited joint set of ODEs are not trivial. 

### The current solution 

This numerically solves the ODE problem 

\[
-\mathbf{L}^{-1}_{sz}\mathbf{M}\frac{d\mathbf{l}_{sz}}{dt} =
-\mathbf{q}_{uz} -
\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
\]

subject to the constraints $\frac{dl_{sz}^{\left[i\right]}}{dt} \leq 0$ if
  $l_{sz}^{\left[i\right]}=l_{szmax}^{\left[i\right]}$ with initial conditions
  $\left.\mathbf{l}_{sz}\right\rvert_{t}$ to give
  $\left.\mathbf{l}_{sz}\right\rvert_{t+\Delta t}$ using the lsoda algorithm in the
`deSolve` package. 

The flows from the saturated zone to the surface excess storage due to
exceeding the maximum lateral flow are denoted $\bar{\mathbf{q}}_{sz}$. They
are computed from
\[
\mathbf{g} = \mathbf{A}^{-1}\left(
\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\left.\mathbf{l}_{sz}\right\rvert_{t+\Delta
  t}+\mathbf{q}_{uz}
\]
for each HRU as
\[
\bar{q}^{\left[i\right]}_{sz} = \left\{
\begin{array}{cc}
  0 & \left. l^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t} <
  l^{\left[i\right]}_{szmax} \\
  g^{\left[i\right]} & \left. l^{\left[i\right]}_{sz}\right\rvert_{t+\Delta t} =
  l^{\left[i\right]}_{szmax} \& g^{\left[i\right]} >0 \\
\end{array}
\right.
\]

An initial estimate of the storage deficit is given by
\[
\tilde{\mathbf{s}}_{sz} = \left. \mathbf{s}_{sz}\right\rvert_{t} +
\Delta t \left.\frac{d\mathbf{s}_{sz}}{dt}\right\rvert_{t+\Delta t}
\]
where the gradient term is evaluated as
\[
\left.\frac{d\mathbf{s}_{sz}}{dt}\right\rvert_{t+\Delta t}=
-\mathbf{q}_{uz} -
\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\left.\mathbf{l}_{sz}\right\rvert_{t
  + \Delta t}
+ \tilde{\mathbf{q}}_{sz}
\]
  
The resulting saturated storage deficit is computed from this as
$$
  \left.\mathbf{s}_{sz}\right\rvert_{t + \Delta t} =
  \max\left( \tilde{\mathbf{s}}_{sz},
  \mathbf{0}\right)
  $$

The estimate of $\mathbf{s}_{uz}$ if now altered to reflect
$\left.\mathbf{s}_{sz}\right\rvert_{t + \Delta t}$.
If $\left.s^{\left[i\right]}_{sz}\right\rvert_{t + \Delta t} =0$ then 
$\left.\mathbf{s}_{uz}\right\rvert_{t + \Delta t} = 0$ and 
$\hat{\mathbf{s}}^{\left[i\right]}_{sz} =
 \bar{\mathbf{s}}^{\left[i\right]}_{sz} -
 \bar{\mathbf{s}}^{\left[i\right]}_{uz}$. 
 Otherwise $\left.\mathbf{s}_{uz}\right\rvert_{t + \Delta t}
			=\bar{\mathbf{s}}^{\left[i\right]}_{uz}$ and $\hat{\mathbf{s}}^{\left[i\right]}_{sz} =
 \bar{\mathbf{s}}^{\left[i\right]}_{sz}$.

The final estimate of the surface excess store can now be computed by adding
the volume of water coming from the saturated zone to give
$$
\left.\mathbf{s}_{ex}\right\rvert_{t+\Delta t} =
\tilde{\mathbf{s}}_{ex} + \Delta t \bar{\mathbf{q}}_{sz} +
\left.\mathbf{s}_{sz}\right\rvert_{t + \Delta t} - \hat{\mathbf{s}}_{sz}
$$

The flow from the saturated zone to the river channels is used to give
$$
\left.\mathbf{s}_{ch}\right\rvert_{t+\Delta t} =
\tilde{\mathbf{s}}_{ch} + \Delta t \mathbf{F}_{sz} \left.\mathbf{l}_{sz}\right\rvert_{t+\Delta
t}$$

#### Comments
1. The most computationally intensive part of algorithm is the numeric
   integration of the $\mathbf{l}_{sz}$. To date this is making larger
   simulations such as the Kent impractical. Avoiding this would make life
   much easier.
2. It is not clear if the above is mass conservative. Note that most
   compuationally expensive operation is the evaluation of 
   $\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}$. However
   this only needs to be evaluated once to get both the flux and storage
   gradient terms. 
   and $\mathbf{q}. This suggests that the potentially more accurate numerical
   solution is to use the \code{deSolve} package to integrate for $\mathbf{l}_{sz}$, $\mathbf{s}_{sz}$ and the integral of
   $\mathbf{q}_{sz}$ may not be that much more computationally expensive.

### An alternative solution

This solution is based on a initial simplification based on subsitution of the
current lateral flux term to give
\[
\mathbf{K} = \left. \mathbf{L}^{-1}_{sz}\right\rvert_{t}\mathbf{M}
\]
All values in $\mathbf{K}$ are greater or equal to zero by definition.

To evaluate $\mathbf{z}$ the contribution to the channel storage from the saturated zone in the current time step let
\[
\mathbf{x} = \left[ \begin{array}{c} \mathbf{s}_{sz} \\
    \mathbf{z} \end{array}\right] 
\]
Taking
\[
\hat{\mathbf{A}} = \left[ \begin{array}{cc} \mathbf{A} & \mathbf{0} \\
    \mathbf{0} & \mathbf{A}_{ch} \end{array} \right]
\]
the evolution of $\mathbf{x}$ to be written as
\[
\hat{\mathbf{A}}\frac{d\mathbf{x}}{dt} =
-\hat{\mathbf{A}} \left[\begin{array}{c} \mathbf{q}_{uz}
    \\ \mathbf{0} \end{array}\right]
- \left[ \begin{array}{cc} \left(\mathbf{W}_{ex}-\mathbf{I}\right) & \mathbf{0} \\
    \mathbf{F}_{ex} & \mathbf{0} \end{array}\right]
\hat{\mathbf{A}}\mathbf{x}
+ \hat{\mathbf{A}} \left[\begin{array}{c} \mathbf{q}_{sz}
    \\ \mathbf{0} \end{array}\right]
\]
or more compactly
\[
\frac{d\mathbf{x}}{dt} =
- \left[\begin{array}{c} \mathbf{q}_{uz}
    \\ \mathbf{0} \end{array}\right]
- \hat{\mathbf{A}}^{-1} \left[ \begin{array}{cc} \left(\mathbf{W}_{ex}-\mathbf{I}\right) & \mathbf{0} \\
    \mathbf{F}_{ex} & \mathbf{0} \end{array}\right]
\hat{\mathbf{A}}\mathbf{x}
+ \left[\begin{array}{c} \mathbf{q}_{sz}
    \\ \mathbf{0} \end{array}\right]
\]

An approximation of the two governing equations can be written as
\[
\left.\mathbf{s}_{sz}\right\rvert_{t+\delta t} -
\left.\mathbf{s}_{sz}\right\rvert_{t}
=  -\int_{\delta t}\mathbf{q}_{uz}dt
- \int_{\Delta
  t}\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
dt
+ \int_{\Delta t} \mathbf{q}_{sz} dt
\]
and
\[
-\mathbf{K}\left( \left.\mathbf{l}_{sz}\right\rvert_{t+\delta t} -
\left.\mathbf{l}_{sz}\right\rvert_{t}\right)
=  -\int_{\delta t}\mathbf{q}_{uz}dt
- \int_{\Delta
  t}\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
dt
+ \int_{\Delta t} \mathbf{q}_{sz} dt
\]
The term $\int_{\delta t}\mathbf{q}_{uz}dt$ is given by the solution of the
previous step. The term 
\[\int_{\Delta
  t}\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
  dt
\]
can be solved using the eigen value method with initial condition
$\left.\mathbf{l}_{sz}\right\rvert_{t}$.
The final term $\int_{\Delta t} \mathbf{q}_{sz} dt$ requires approximation and
is absed on the bounds on the storage and flux variables.

Following a similar pattern to earlier solutions we derive unbounded estimates as
\[
\bar{\mathbf{s}}_{sz} = 
\left.\mathbf{s}_{sz}\right\rvert_{t}
-\int_{\delta t}\mathbf{q}_{uz}dt
- \int_{\Delta
  t}\mathbf{A}^{-1}\left(\mathbf{W}_{sz}-\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
dt
\]
and 
\[
\bar{\mathbf{l}}_{sz} = 
\left.\mathbf{l}_{sz}\right\rvert_{t}
+\mathbf{K}^{-1}\left(\int_{\delta t}\mathbf{q}_{uz}dt
+ \int_{\Delta
  t}\mathbf{A}^{-1}\left(\mathbf{W}_{sz}+\mathbf{I}\right)\mathbf{A}\mathbf{l}_{sz}
dt\right)
\]


Since $\mathbf{q}_{sz} \geq 0$ 
\[
\int_{\Delta t} \mathbf{q}_{sz} dt \geq 0
\]
Since  $\mathbf{s}_{sz} \geq 0$
\[
\int_{\Delta t} \mathbf{q}_{sz} dt \geq -\bar{\mathbf{s}}_{sz}
\]
Since  $0 \leq \mathbf{l}_{sz} \leq \mathbf{l}_{szmax}$
\[
\mathbf{K}\bar{\mathbf{l}} \geq \int_{\Delta t} \mathbf{q}_{sz} dt \geq \mathbf{K}\left(\bar{\mathbf{l}}_{sz}-\mathbf{l}_{szmax}\right)
\]

Take $\int_{\Delta t} \mathbf{q}_{sz} dt$ to be the smallest
value satifying the upper limits on flow and saturation, that is
\[
\int_{\Delta t} \mathbf{q}_{sz} dt = \max\left(\mathbf{0},-\bar{\mathbf{s}}_{sz},\mathbf{K}\left(\bar{\mathbf{l}}_{sz}-\mathbf{l}_{szmax}\right)\right)
\]
This gives
\[
\left.\mathbf{s}_{sz}\right\rvert_{t+\Delta t} = \bar{\mathbf{s}}_{sz} + \max\left(\mathbf{0},-\bar{\mathbf{s}}_{sz},\mathbf{K}\left(\bar{\mathbf{l}}_{sz}-\mathbf{l}_{szmax}\right)\right) 
\]
and
\[
\left.\mathbf{l}_{sz}\right\rvert_{t+\Delta t} = \max\left(\mathbf{0},
\bar{\mathbf{l}}_{sz} -\mathbf{K} \max\left(\mathbf{0},-\bar{\mathbf{s}}_{sz},\mathbf{K}\left(\bar{\mathbf{l}}_{sz}-\mathbf{l}_{szmax}\right)\right) \right)
\]
where the maximum ensures a non-negative flux in the case that the upper limit
on $\int_{\Delta t} \mathbf{q}_{sz} dt$ is not met.

#### Comments
1. alsdkjf

## Step 6: Estimating Channel Flow
The average flow to the channels over the time step in cumecs is given by 
$$\frac{ \mathbf{A}_{ch} \left.\mathbf{s}_{ch}\right\rvert_{t+\Delta t}}{3600\Delta t}$$


# Ordinary Differential Equations Solutions

For completeness the solutions to the ODEs made use of above are
documented here.

## Single variable non-homogeneous ODE with constant input

The initial condition
problem$$\frac{dx\left(t\right)}{dt} = a - b x\left(t\right) \quad x\left(0\right) = x_0$$
or more compactly
$$x^{\prime}\left(t\right) = a - b x\left(t\right) \quad x\left(t_0\right) = x_0$$
involves the solution of first order linear system. This can be solved
explicitly using an ‘integrating factor’. Let
$\mu = \exp\left(\int\limits_t b dt\right) = \exp\left(bt\right)$.
Multiplying both sides by $\mu$ then integrating (noting the LHS is the
result of the product formula in differentiation) gives
$$\exp\left(bt\right) x = \int\limits_{t} a\exp\left(bt\right) dt = \frac{a}{b}\exp\left(bt\right) + K$$
The constant $K$ can be evaluates using the initial conditions as
$K=x_{0}-\frac{a}{b}$. Substitution and rearrangement then gives
$$x = x_{0}\exp\left(-bt\right) + \frac{a}{b}\left(1-\exp\left(-bt\right)\right)$$
Note that $$\begin{array}{c}
        x\rightarrow0 \quad\mathrm{as}\quad b\rightarrow\infty\\
        x\rightarrow x_{0} + at \quad\mathrm{as}\quad b\rightarrow0\\
    \end{array}$$

## Multiple variable homogeneous ODE

The solution to the initial value problem
$$\frac{d\mathbf{x}\left(t\right)}{dt} = \mathbf{A} \mathbf{x}\left(t\right) \quad \mathbf{x}\left(t_0\right) = \mathbf{x}_0$$
or more compactly
$$\mathbf{x}^{\prime}\left(t\right) = \mathbf{A} \mathbf{x}\left(t\right) \quad \mathbf{x}\left(t_0\right) = \mathbf{x}_0$$
is computed using the eigen value method.

Suppose $\mathbf{x}$ is of length $n$ and $\mathbf{A}$ has suitably unique eigen values
$\mathbf{\lambda}$. Taking $\mathbf{M}$ to be the matrix of eigen vectors
$$
\mathbf{x}\left(t\right) = \mathbf{M} \left[\begin{array}{c}
c_1 \exp\left(\lambda_1t\right) \\
\vdots \\
c_n \exp\left(\lambda_nt\right)
\end{array}
\right]
$$
where the constant $\mathbf{c}$ can be estimated from the initial conditions
at time 0 as
$$ \mathbf{c} = \mathbf{M}^{-1} \mathbf{x}_{0} $$


<!-- By the method of “Variation of Parameters for Systems” the solution to -->
<!-- the initial value problem -->
<!-- $$\frac{d\mathbf{x}\left(t\right)}{dt} = \mathbf{a} - \mathbf{B} \mathbf{x}\left(t\right) \quad \mathbf{x}\left(t_0\right) = \mathbf{x}_0$$ -->
<!-- or more compactly -->
<!-- $$\mathbf{x}^{\prime}\left(t\right) = \mathbf{a} - \mathbf{B} \mathbf{x}\left(t\right) \quad \mathbf{x}\left(t_0\right) = \mathbf{x}_0$$ -->
<!-- is given by -->
<!-- $$\mathbf{x}\left(t\right) = e^{\mathbf{B}t}\mathbf{x}_0 + e^{\mathbf{B}t}\int_{t_0}^{t} e^{r\mathbf{B}} \mathbf{a} dr$$ -->
