// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hs_init_cpp
void hs_init_cpp(DataFrame hillslope, const List sqnc, const double q0);
RcppExport SEXP _dynatop_hs_init_cpp(SEXP hillslopeSEXP, SEXP sqncSEXP, SEXP q0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type hillslope(hillslopeSEXP);
    Rcpp::traits::input_parameter< const List >::type sqnc(sqncSEXP);
    Rcpp::traits::input_parameter< const double >::type q0(q0SEXP);
    hs_init_cpp(hillslope, sqnc, q0);
    return R_NilValue;
END_RCPP
}
// hs_sim_cpp
void hs_sim_cpp(DataFrame hillslope, const DataFrame channel, const List sqnc, const NumericMatrix obs, const List ts, NumericMatrix channel_inflow, bool mass_check, NumericMatrix mass_errors, LogicalVector keep_states, List state_record);
RcppExport SEXP _dynatop_hs_sim_cpp(SEXP hillslopeSEXP, SEXP channelSEXP, SEXP sqncSEXP, SEXP obsSEXP, SEXP tsSEXP, SEXP channel_inflowSEXP, SEXP mass_checkSEXP, SEXP mass_errorsSEXP, SEXP keep_statesSEXP, SEXP state_recordSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type hillslope(hillslopeSEXP);
    Rcpp::traits::input_parameter< const DataFrame >::type channel(channelSEXP);
    Rcpp::traits::input_parameter< const List >::type sqnc(sqncSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const List >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type channel_inflow(channel_inflowSEXP);
    Rcpp::traits::input_parameter< bool >::type mass_check(mass_checkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mass_errors(mass_errorsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type keep_states(keep_statesSEXP);
    Rcpp::traits::input_parameter< List >::type state_record(state_recordSEXP);
    hs_sim_cpp(hillslope, channel, sqnc, obs, ts, channel_inflow, mass_check, mass_errors, keep_states, state_record);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynatop_hs_init_cpp", (DL_FUNC) &_dynatop_hs_init_cpp, 3},
    {"_dynatop_hs_sim_cpp", (DL_FUNC) &_dynatop_hs_sim_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynatop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
