#' Initialises the hru states
#'
#' @description The states of the hru are the timevarying characteristics that describe the hru state, they can be both fluxes and storage volumes
#'
#' @param hillslope a property object as generated by initialise_properties with type hillslope
#' @param channel a property object as generated by initialise_properties with type channel
#' @param Wsat weighted conectivity matrix for saturated zone
#' @param init_discharge steady outflow presumed sum of hillslope saturateed flows [m^3/s]
#' @return hillslope with additional feilds relating to the states
#' @name initialise_hru
#' @rdname initialise_hru
NULL

#' Hillslope initialisation
#' @export
#' @rdname initialise_hru
initialise_hillslope <- function(hillslope,model,init_discharge){

    ## compute the max flow from saturated area
    hillslope$lsz_max <- exp(hillslope$ln_t0-hillslope$atb_bar)
        
    ## initialise based on the sum of the lateral flow from the saturated zone to all channle elements being init_discharge. If not proportion by area
    total_hillslope_area <- sum(hillslope$area)
    q_0 <- init_discharge*3600/total_hillslope_area # q_0 is specific area recharge in mm/hr
    hillslope$lsz <- q_0 # assume constant across catchment
    try({
        hillslope$lsz <- solve( diag(nrow(model$Wsat)) - model$Wsat,
                               q_0*hillslope$area) / hillslope$area
        names(hillslope$lsz) <- NULL
        if(any( hillslope$lsz <= 0 )){
            stop("Solution for saturated zone initialisation produced negative or zero flows.\n Using constant recharge across catchment")
        }
    })
    hillslope$lsz <- pmin( hillslope$lsz , hillslope$lsz_max )
    
    ## compute the saturated zone storage deficit based on the flow
    hillslope$ssz <- -hillslope$m * (log(hillslope$lsz)-hillslope$ln_t0+hillslope$atb_bar)

    ## assume full recharge from saturated zone
    hillslope$quz <- hillslope$lsz

    ## unsaturated storage by inverse of eqn for q_uz in Beven & Wood 1983
    hillslope$suz <- hillslope$quz * hillslope$td * hillslope$ssz

    ## initialise root zone based on fraction constrained within 0,1
    hillslope$srz <- pmax( pmin( hillslope$srz_0, 1) ,0 ) * hillslope$srz_max

    ## initialise surface storage to 0
    hillslope$ex <- rep(0,length(hillslope$id))

    return(hillslope)
}


#' Channel initialisation
#' @export
#' @rdname initialise_hru
initialise_channel <- function(channel){
    channel$store <- rep(0,length(channel$id))
    return(channel)
}
