# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multi_hsu_cpp <- function(id, states, properties, flow_dir, ext_idx, channel_id, channel_area, channel_ext_idx, ext_rec, channel_inflow, keep_states, state_rec, timestep, n_sub_step) {
    invisible(.Call(`_dynatop_multi_hsu_cpp`, id, states, properties, flow_dir, ext_idx, channel_id, channel_area, channel_ext_idx, ext_rec, channel_inflow, keep_states, state_rec, timestep, n_sub_step))
}

single_hsu_cpp <- function(state_rec, ext_rec, flux_rec, properties, timestep, n_sub_step) {
    invisible(.Call(`_dynatop_single_hsu_cpp`, state_rec, ext_rec, flux_rec, properties, timestep, n_sub_step))
}

